export default {
 E064:{title:'Connect wide-area transmission, addressing and a local network',commandWord:'State / Explain / Complete / Draw / Describe',
 reading:['Work through five different answer forms. Compare WAN with LAN directly, explain cellular transmission as a process, use exact terms in the blanks, and count every device before drawing the star.'],
 solution:['6(a): A WAN links devices over a larger geographical area than a LAN. A WAN may use transmission media owned by external providers, whereas the LAN’s media are usually owned by the organisation.', '6(b): The coverage area is divided into cells. Each cell has a tower with an antenna that sends and receives data. A phone communicates with the local tower using low-power radio signals. The tower can support communication with multiple phones at the same time.', {type:'table',headers:['6(c): blank in order','Answer'],rows:[['1','full stops'],['2','hexadecimal'],['3','zeros'],['4','128'],['5','dynamic'],['6','private']]}, {type:'diagram',name:'review-star'}, '6(d): Each labelled computer, printer, server and router has its own connection to the central switch; the router connects to the internet. This supplies all eight local device connections requested.', '6(e): A switch learns or stores which MAC addresses are reachable through its ports. It receives data and uses the destination MAC address to forward it to the intended device’s port rather than every port when that destination is known.'],
 marking:['The subpart limits are 2, 4, 6, 4 and 3. In (d), the four marks cover server connection, all four computers, both printers, and internet access; they are not one mark per device. The official scheme allows the printers to connect through a server or computer as well.', 'The IP passage uses a simplified local-network description. A private address is not publicly routed on the internet; properly routed private networks can communicate beyond a single LAN. This clarification does not change the required word in the original blank.'],
 mistakes:['A star must have the switch at its centre. Four computer boxes with one shared chain do not show four direct connections. A MAC address is used for local switching; an IP address is not a replacement for it in part (e).']},
 E065:{title:'Review relationships, table definitions, queries and access control',commandWord:'Complete / Write / Describe',
 reading:['All four subparts use the same database. Trace the foreign keys into COMPLAINT, then use the STAFF sample to choose types. The query must return only three fields and include products rated exactly 5.'],
 solution:[{type:'diagram',name:'review-er'}, '5(a): CUSTOMER, PRODUCT and STAFF each have a one-to-many relationship with COMPLAINT. A complaint references one row in each of those tables.', {type:'code',text:'CREATE TABLE STAFF(\n    StaffID INTEGER NOT NULL,\n    StaffFirstName VARCHAR(40),\n    StaffLastName VARCHAR(40),\n    Department CHAR(1),\n    RemoteWorker BOOLEAN,\n    PRIMARY KEY (StaffID)\n);\n\nSELECT PRODUCT.ProductID, ProductName, ComplaintDetails\nFROM PRODUCT INNER JOIN COMPLAINT\nON PRODUCT.ProductID = COMPLAINT.ProductID\nWHERE Rating <= 5\nORDER BY Rating DESC;'}, '5(b): The text lengths are teacher choices for the examples. The Yes/No sample represents a Boolean property. 5(c): The join supplies complaint text for each matching product; a product can appear more than once when it has several complaints. Rating controls filtering and sorting without being selected as an output field.', '5(d): Authentication checks credentials before allowing access to customer data. Access rights then restrict which authenticated users may read or change that data.'],
 marking:['Part (a) gives one mark per correct relationship, to three. Part (b) groups its four marks into CREATE structure, the three text types, the remaining two types, and the primary key. Part (c) gives five clause-related points. Part (d) gives one mark for each of two methods and one for each matching description.'],
 mistakes:['A missing join creates unrelated product/complaint pairs. Rating < 5 wrongly excludes the boundary value 5; ASC reverses the requested order. Authentication and authorisation answer different questions.']},
 E066:{title:'Justify compression for a live concert',commandWord:'Identify / Justify',
 reading:['Tick one option and justify it for real-time delivery. The scheme permits either choice when supported by suitable conditions.'],
 solution:['Tick lossy. Reducing the amount of data needed per second reduces the bandwidth required for the live stream, so subscribers are less likely to experience buffering. The discarded detail can be chosen so that the loss of quality is not noticeable to the intended viewers.'],
 marking:['The maximum is three. The official scheme also accepts lossless with suitable reasoning, such as sufficient bandwidth and a need to preserve quality. Do not treat the teacher’s selected option as the only permitted answer.'],
 mistakes:['“It makes the file smaller” needs the consequence for live viewing. Do not claim that all lossy compression has no perceptible effect at every setting.']}
};
