import section12 from './section-12.mjs';
export default {
 E108:{title:'Validate sensor readings and sort paired data',commandWord:'Complete / Write',
 reading:['Part (a) revisits the test plan from Lesson 089. In part (b), speed determines order but the sensor ID must stay with its speed. Use the given 2000 rows and improve bubble sort with a no-swap test and a shrinking boundary.'],
 solution:[...section12.E104.solution, {type:'code',text:'PROCEDURE Sort()\n    DECLARE Temp, J, Boundary : INTEGER\n    DECLARE NoSwaps : BOOLEAN\n    Boundary ← 1999\n    REPEAT\n        NoSwaps ← TRUE\n        FOR J ← 1 TO Boundary\n            IF Reading[J, 1] > Reading[J + 1, 1] THEN\n                Temp ← Reading[J, 1]\n                Reading[J, 1] ← Reading[J + 1, 1]\n                Reading[J + 1, 1] ← Temp\n                Temp ← Reading[J, 2]\n                Reading[J, 2] ← Reading[J + 1, 2]\n                Reading[J + 1, 2] ← Temp\n                NoSwaps ← FALSE\n            ENDIF\n        NEXT J\n        Boundary ← Boundary - 1\n    UNTIL NoSwaps OR Boundary = 0\nENDPROCEDURE'}, 'Each pass moves the largest remaining speed to the end of the unsorted region. Swapping both columns preserves every speed/ID pair. Reset NoSwaps at the start of each pass; leave it TRUE only when no exchange occurs. The extra Boundary = 0 condition ends after the final required pass. The official example uses the no-swap condition alone.', {type:'table',headers:['Teacher three-row demonstration','Rows as (speed, ID)'],rows:[['Start','(40, 7), (10, 3), (30, 9)'],['After first comparison','(10, 3), (40, 7), (30, 9)'],['After second comparison / pass 1','(10, 3), (30, 9), (40, 7)'],['Pass 2: no swap; stop','(10, 3), (30, 9), (40, 7)']]}],
 marking:['Part (a) is four marks and repeats the earlier test-plan item. Part (b) lists nine possible points with an eight-mark cap. Both the paired swaps and the no-swap mechanism have explicit marking requirements; sorting only speeds is incomplete.'],
 mistakes:['Comparing J = 2000 with J + 1 accesses a nonexistent row. Setting NoSwaps only once prevents the early-exit logic from reflecting the current pass. Equal speeds need no swap.']},
 E109:{title:'Combine modules with safe file processing',commandWord:'Suggest / Give / Write',
 reading:['Part (b)’s DeleteSpaces interface is provided as context only. For part (c), call both supplied functions, preserve existing output-file content and count lines that become empty after processing.'],
 solution:['8(a): Separating stages makes each task easier to design and debug. Keeping a different output file from each stage lets the teacher inspect intermediate results and check where an error first appears.', {type:'code',text:'PROCEDURE Stage_2(F1 : STRING, F2 : STRING)\n    DECLARE Line : STRING\n    DECLARE Count : INTEGER\n    Count ← 0\n    OPENFILE F1 FOR READ\n    OPENFILE F2 FOR APPEND\n    WHILE NOT EOF(F1)\n        READFILE F1, Line\n        Line ← DeleteSpaces(Line)\n        Line ← DeleteComment(Line)\n        IF Line <> "" THEN\n            WRITEFILE F2, Line\n        ELSE\n            Count ← Count + 1\n        ENDIF\n    ENDWHILE\n    CLOSEFILE F1\n    CLOSEFILE F2\n    OUTPUT Count, " blank lines were removed"\nENDPROCEDURE'}, 'Store each returned string back into Line; merely calling a function does not replace the text. Test for an empty string after both transformations. An empty input file appends nothing and reports zero. A comment-only line can become empty and must be counted rather than written. OPENFILE/CLOSEFILE use the current guide’s notation; the official example below retains its historical OPEN/CLOSE notation.'],
 marking:['Part (a) gives one mark for a reason and one for the benefit of separate files. Part (c) gives eight points, including opening/closing both files as one group and assigning both function returns as one group. Use APPEND because the output file already exists and is to receive the copied lines.'],
 mistakes:['WRITE mode can erase existing output. Checking for blank lines before removing leading spaces and comments misses lines that become blank. Reimplementing the two supplied functions ignores the requirement to use them.']}
};
