export default {
 E039:{title:'Link two OS management tasks to multitasking',commandWord:'Explain',
 reading:['Explain both memory management and process management in terms of multiple active programs. Avoid spending the whole answer on just one task.'],
 solution:['Memory management keeps data for the active programs in RAM and protects their allocated areas so that one program does not overwrite another’s data.', 'Process management schedules which process runs next, pauses one when necessary and switches the processor to another. This lets processes share processor time and make progress.'],
 marking:['The total is four marks, with no more than three from either management task. This model supplies two memory points and two process points. The official list contains alternatives; listing every alternative still cannot exceed four.'],
 mistakes:['Giving four memory facts cannot bypass the three-mark memory cap. Multitasking does not mean that one processor core executes every process simultaneously.']},
 E040:{title:'Define a library and explain two DLL benefits',commandWord:'Define / Explain',
 reading:['Define the reusable resource first. For each DLL benefit, explain why dynamic linking produces that benefit for the developer.'],
 solution:['7(a)(i): A program library is a collection of pre-written or pre-compiled subroutines that other programs can import and call.', {type:'table',headers:['7(a)(ii): benefit','Explanation'],rows:[['Smaller application executable','The application file does not contain all the library routines; the required library is separate.'],['No need to recompile the main program for a compatible DLL correction','The DLL can be corrected independently while its existing interface remains usable by the application.']]}],
 marking:['The definition is capped at two marks. The DLL answer is marked in two pairs: one mark for each benefit and one for a corresponding expansion. Unrelated facts beside a benefit do not supply its explanation.'],
 mistakes:['Calling a library a folder of data files misses reusable subroutines. A compatible interface is needed for safe separate replacement; a changed parameter contract can still require application changes.']},
 E041:{title:'Choose a utility that meets an exclusion',commandWord:'Identify / Explain',
 reading:['The question excludes utilities intended to improve security. Choose a maintenance tool and explain the problem that makes it useful.'],
 solution:['Defragmentation software. Saving and deleting files can leave a file split across separate parts of a magnetic disk. Defragmentation places the file’s blocks contiguously, reducing head movement and improving access time.'],
 marking:['One mark is for the utility name and two are for the explanation. The scheme also permits appropriate disk-repair, compression or formatting examples with their reasons.'],
 mistakes:['Antivirus does not satisfy the exclusion. Do not present magnetic-disk head movement as an SSD mechanism, or guarantee that disk repair can recover every corrupted file.']},
 E042:{title:'Use translation tools at different development stages',commandWord:'Explain',
 reading:['The question supplies the order: interpreter first, compiler later. Explain what the programmer gains at each stage.'],
 solution:['While coding, the programmer can use an interpreter to test and debug partially completed code, observe errors and try corrections promptly.', 'After completing the program, the programmer can compile it to produce an executable. That executable can be distributed without supplying the source and run repeatedly without re-interpreting the source each time.'],
 marking:['At most two marks come from the interpreter section and at most two from the compiler section. Four generic compiler advantages do not answer the whole question.'],
 mistakes:['Do not say the interpreter produces a saved executable as its normal result. The compiler does not prove that a syntactically correct program fulfils the requirements.']},
 E043:{title:'Justify a translator choice during development',commandWord:'Identify / Justify',
 reading:['The team is still writing the program. State a choice, then give reasons tied to testing and correction at that stage.'],
 solution:['An interpreter is suitable. The developer can test incomplete sections, rather than wait for the whole program to be finished. Changes can be tried promptly so their effects are visible, supporting debugging as each section is developed.'],
 marking:['The choice itself earns no mark. Up to three marks are for justification. The scheme also accepts a justified compiler choice, such as producing an executable for repeated tests without recompiling unchanged code. This is not a question with only one creditworthy label.'],
 mistakes:['“Interpreter because it is easier” has no technical support. Do not reject every compiler answer when the official scheme explicitly allows a supported alternative.']},
 E044:{title:'Describe the supplied IDE features precisely',commandWord:'Complete / Describe',
 reading:['The four feature names are already supplied. Describe the behaviour of each; avoid giving the same debugging description in every row.'],
 solution:[{type:'table',headers:['Feature','Description'],rows:[['Breakpoints','Pause execution at a selected line so current values or progress can be inspected.'],['Dynamic syntax checks','Highlight syntax errors while code is being entered.'],['Context-sensitive prompts','Suggest appropriate code or complete a statement for the current context.'],['Single stepping','Execute one statement or line at a time and pause so values can be checked.']]}],
 marking:['Each distinct correct description earns one mark. Merely copying the feature name back into its description does not provide the behaviour.'],
 mistakes:['Syntax highlighting is not proof that the algorithm is correct. A breakpoint pauses at a chosen location; stepping controls subsequent individual execution.']}
};
