export default {
 E045:{title:'Separate privacy from integrity',commandWord:'State',
 reading:['These are two one-mark definitions. State the essential property of each; examples of attacks are not required.'],
 solution:['5(a): Privacy means that data is accessed by or disclosed to authorised people only.', '5(b): Integrity means that data remains accurate, complete and consistent during and after processing.'],
 marking:['Each subpart has a one-mark maximum. The scheme also accepts data being up to date for integrity; listing all acceptable words does not multiply the mark.'],
 mistakes:['Data can be accurate but disclosed to the wrong person, or kept private but entered incorrectly. These properties are independent.']},
 E046:{title:'Respect the exclusion of authentication',commandWord:'Identify / Describe',
 reading:['Authentication is already given. Choose another protective measure, then explain its operation on connections to the assessment server.'],
 solution:['A firewall. It checks incoming connections or traffic against configured rules and blocks traffic that does not satisfy those rules, for example connections to disallowed ports.'],
 marking:['One mark is for the security measure and up to two for how that measure works. A proxy-server explanation is also permitted by the official scheme.'],
 mistakes:['Passwords, biometric login and two-factor login are authentication answers and ignore “one other”. Naming several tools does not replace explaining one.']},
 E047:{title:'Describe phishing and spyware as different mechanisms',commandWord:'Describe',
 reading:['Explain the two named threats separately. One deceives a person into disclosure; the other secretly collects activity on a computer.'],
 solution:['A phishing email pretends to come from a trusted or official organisation and tries to persuade the recipient to disclose private information, often through a link to an imitation login page.', 'Spyware is malicious software installed without the user’s knowledge that secretly records activity such as keystrokes and sends the collected information to a third party.'],
 marking:['Phishing and spyware each have a maximum of two marks, giving four overall. The scheme lists several spyware details; an extended spyware paragraph cannot compensate for omitting phishing.'],
 mistakes:['An unwanted advertisement alone does not explain phishing. A phishing message does not have to install spyware to cause disclosure.']},
 E048:{title:'Protect data during transmission',commandWord:'Identify / Describe',
 reading:['Protect the content while it travels between the assessment server and its destination. Explain what an interceptor would see and how the intended recipient can recover the data.'],
 solution:['Encryption transforms the readable data into ciphertext using an algorithm and a key. Someone who intercepts the transmission cannot understand its content without the required decryption key. The intended recipient uses the appropriate key and algorithm to recover the readable data.'],
 marking:['One mark is for identifying encryption and up to two for its operation or purpose. The official alternatives include scrambling, unreadability if intercepted, and the key/algorithm needed to decode it.'],
 mistakes:['Encryption does not prevent interception itself and does not, by itself, prove that the data has not been altered. Keep confidentiality separate from integrity.']},
 E049:{title:'Classify verification methods and follow grouped marking',commandWord:'Draw',
 reading:['Draw one line from each of the four methods. Data entry and data transfer are the two contexts, not interchangeable names for validation.'],
 solution:[{type:'table',headers:['Verification method','Connect to'],rows:[['Parity byte check','Data transfer'],['Checksum','Data transfer'],['Visual check','Data entry'],['Parity block check','Data transfer']]}],
 marking:['The official rule gives one mark for two or three correct connections and two marks for all four. It is not one mark per line. The official diagram below preserves the exact connections.'],
 mistakes:['Visual verification compares entered data with its source. A range check would test whether an input is plausible; it is not one of these supplied verification methods.']},
 E050:{title:'Describe two transmission-verification methods',commandWord:'Identify / Describe',
 reading:['The robot-to-computer link transfers data. Give two suitable methods and pair each name with its own detection process.'],
 solution:[{type:'table',headers:['Method','Description'],rows:[['Parity byte check','The sender includes a parity bit so the byte has the agreed odd or even number of 1s. The receiver checks that parity; a mismatch indicates an error.'],['Checksum','The sender calculates a value from the data and sends it with the data. The receiver repeats the same calculation and compares the result with the received checksum; a mismatch indicates an error.']]}],
 marking:['Each method-and-description pair can earn two marks, four in total. The official scheme also describes parity block checking as another valid method.'],
 mistakes:['A matching checksum or parity does not guarantee that no error occurred: some changes preserve the check value. Encryption is a security mechanism, not a replacement for either requested verification description.']}
};
