export default {
 E021:{title:'Recognise embedded-system features and limits',commandWord:'Identify',
 reading:['Use the factory-machine context. Two features are requested, followed by one drawback; a list of machine examples would not answer either task.'],
 solution:['1(c)(i): An embedded system is built into a larger machine and is dedicated to a single task or a limited set of functions.', '1(c)(ii): It can be difficult for an ordinary user to update or adapt its firmware for a different task.'],
 marking:['Each distinct feature can earn one mark, up to two. The drawback has a separate one-mark limit. The scheme allows other limitations such as specialist repair or upgrading.'],
 mistakes:['Small size alone does not explain the system’s embedded role. A processor, memory and I/O can be present even though the computer is not a separate desktop device.']},
 E022:{title:'Complete a VR-headset mechanism',commandWord:'Complete',
 reading:['Read the whole sentence around each blank. Distinguish the image-output component, the head-motion sensor, the measured movement and the eye-tracking input.'],
 solution:[{type:'table',headers:['Blank, in order','One accepted completion'],rows:[['1','LCD displays'],['2','gyroscope'],['3','direction'],['4','digital cameras']]},'The displays deliver images to the user. A gyroscope detects head movement; the processor uses the data to identify its direction. Eye-tracking cameras supply a different input: images of the eyes for analysis.'],
 marking:['One mark is awarded per correctly completed statement. The official scheme permits alternatives such as screens/lenses, accelerometer and speed in the appropriate blanks. These are alternatives, not extra blanks or extra marks.'],
 mistakes:['A speaker does not detect head movement. Keep the eye camera separate from the sensor used to track the head.']},
 E023:{title:'Connect touch detection to the selected menu item',commandWord:'Explain',
 reading:['The requested endpoint is a menu selection. Explaining a physical sensor without connecting it to coordinates and software leaves the task incomplete.'],
 solution:['A capacitive touchscreen detects a change in charge at the point touched. An alternative resistive design detects contact between two layers that completes a circuit.', 'The detected location determines x and y coordinates. The software checks which menu item occupies that position and adds the corresponding item to the restaurant’s order.'],
 marking:['The official scheme splits the four available marks into at most two for touch-detection methods and at most two for menu selection. The first paragraph supplies two accepted alternative detection methods; the second supplies coordinates and matching the menu item. They are alternative screen designs, not a claim that a single screen must use both.'],
 mistakes:['Listing four sensor technologies cannot bypass the detection-group maximum. “The screen knows what was touched” omits the coordinate-to-menu mapping.']},
 E024:{title:'Compare RAM types and explain a disk buffer',commandWord:'Identify / Explain',
 reading:['Part (a) requires paired differences. In (b), identify which device sends faster and follow data through temporary storage to the slower disk.'],
 solution:['2(a): DRAM needs periodic refreshing; SRAM does not need refreshing while power is maintained. DRAM generally has a slower access time than SRAM.', '2(b): The computer can supply data faster than the magnetic hard disk can write it. It first places data in a memory buffer, which stores it temporarily. The computer can continue other work while the disk removes data from the buffer at its slower rate. A finite buffer can fill, so further transfers must wait when there is no free capacity.'],
 marking:['Part (a) awards one mark per difference. In (b), up to four points cover the speed mismatch, temporary storage, fast transfer into the buffer, reduced waiting and slower transfer out. The capacity qualification explains the limit; it is not an additional official mark.'],
 mistakes:['Both RAM types are volatile. Refresh is not the same as retaining data after power is removed. A buffer does not increase the physical disk’s write speed.']},
 E025:{title:'Classify a bridge warning system',commandWord:'Identify / Explain',
 reading:['For each sensor, give its use in this particular system. In (b), explain whether the system itself changes the situation being measured; a warning can still require the driver to act.'],
 solution:[{type:'table',headers:['Sensor','Use'],rows:[['Infrared sensor','Checks the vehicle’s height.'],['Pressure sensor','Checks the vehicle’s weight.']]},'9(b): This is a monitoring system. Turning on the warning sign informs the driver; it does not itself change the vehicle’s height or weight or feed a corrective change back to those sensor inputs. The system has no actuator that automatically stops the vehicle.'],
 marking:['Part (a) gives one mark for each suitable sensor-and-use pair. In (b), identification alone earns no mark: the two marks are for correct justification, such as the indicator-only output and absence of corrective feedback.'],
 mistakes:['Do not award yourself a mark just for writing “monitoring”. The human driver’s response is not an automatic actuator in the specified warning system.']},
 E026:{title:'Classify an automatic door system',commandWord:'Identify / Justify',
 reading:['Explain what changes physically, how this affects subsequent sensing, and why the system can respond without a person operating a switch.'],
 solution:['It is a control system. An actuator opens or closes the doors. Opening the doors allows people to move through, changing whether a person is detected within two metres. The system then responds autonomously to the new sensor input and closes the doors when nobody remains within that distance.'],
 marking:['The label “control system” earns no mark here. The three marks concern the actuator, the effect of opening on subsequent sensed input, and autonomous action using feedback.'],
 mistakes:['Giving only “uses a sensor” does not distinguish control from monitoring. Include the door’s physical action and the next input change.']},
 E027:{title:'State complete two-input gate conditions',commandWord:'Describe',
 reading:['Give the complete condition for output 1 or output 0, with the other cases accounted for. These are individual gates, not a request for a compound circuit.'],
 solution:[{type:'table',headers:['Gate','Operation'],rows:[['NAND','Output 0 only when both inputs are 1; otherwise output 1.'],['NOR','Output 1 only when both inputs are 0; otherwise output 0.'],['XOR','Output 1 when the two inputs differ; otherwise output 0.'],['OR','Output 0 only when both inputs are 0; otherwise output 1.']]}],
 marking:['Each correct gate operation earns one mark. Equivalent complete wording is acceptable; repeating a gate’s name does not describe its operation.'],
 mistakes:['For XOR, “one input is 1” needs to exclude both being 1. OR does include the both-1 case.']},
 E028:{title:'Translate two different logic expressions',commandWord:'Draw / Complete',
 reading:['Parts (a) and (b) use different expressions. Preserve the brackets and input names in each; do not reuse the circuit expression for the truth table.'],
 solution:[{type:'table',headers:['6(a): stage','Connections'],rows:[['First branch','Connect R and S to an XOR gate.'],['Second branch','Connect T to NOT; connect NOT T and P to a NOR gate.'],['Final output','Connect the XOR output and NOR output to an AND gate, labelled Z.']]},'Use standard gate symbols for those connections. The official circuit below shows the complete drawing.',
 {type:'table',headers:['P','Q','R','NOT P OR Q','R NOR Q','Z'],rows:[[0,0,0,1,1,0],[0,0,1,1,0,1],[0,1,0,1,0,1],[0,1,1,1,0,1],[1,0,0,0,1,1],[1,0,1,0,0,0],[1,1,0,1,0,1],[1,1,1,1,0,1]]},'For example, P=1,Q=0,R=0 makes the two final XOR inputs 0 and 1, so Z=1.'],
 marking:['6(a) groups XOR and the final AND with their connections for one mark, and NOT plus NOR with their connections for the other. In 6(b), the first four correct output rows earn one mark and the last four earn one mark. There is no separate official mark for each row.'],
 mistakes:['NOR means NOT of the OR result, not NOT of one input. Completing only one row correctly in each group does not earn the group’s mark.']}
};
