export default {
 E067:{title:'Select information for an email module',commandWord:'State / Identify / Justify',
 reading:['Decide what this module needs, not what the entire shop system stores. Pair every selected or rejected item with a reason.'],
 solution:[{type:'table',headers:['7(a)(i): needed','Reason'],rows:[['Email address','To deliver the email to the customer.'],['Product category preference','To select products that interest the customer.'],['Contact preference','To check that the customer accepts contact by email.']]}, {type:'table',headers:['7(a)(ii): not needed','Reason'],rows:[['Postal address','The module sends an email, not a posted letter.'],['Payment details','No purchase or payment is being processed by this module.']]}],
 marking:['Each information-and-justification pair earns one mark, to three in (i) and two in (ii). The scheme accepts order history in either category when the reason matches the chosen design; classification alone is insufficient.'],
 mistakes:['Do not reject an item simply because it is private. Explain whether it is needed for this module’s specified task.']},
 E068:{title:'Decompose a waiting-list notification module',commandWord:'Identify / Describe',
 reading:['Suggest three distinct submodules and describe their jobs in the text-message workflow. Names alone do not earn the paired marks.'],
 solution:[{type:'table',headers:['Submodule','Use'],rows:[['GetMemberPhoneNumber','Retrieve the mobile number of a member on the class waiting list.'],['CreateMessage','Build a text message identifying the class with an available space.'],['SendMessage','Send that message to the waiting-list member’s mobile number.']]}],
 marking:['One mark is available for each module with its corresponding use, up to three. Identifying interested members is another accepted submodule.'],
 mistakes:['“Input, process, output” without the task performed is too vague. An email submodule would not match the required text-message channel.']},
 E069:{title:'Complete an identifier table',commandWord:'Complete',
 reading:['Every row needs both a meaningful variable name and a type that preserves the example value.'],
 solution:[{type:'table',headers:['Meaning','Variable name','Data type'],rows:[['Customer name','CustomerName','STRING'],['Number of items','NumItems','INTEGER'],['New customer indicator','NewCustomer','BOOLEAN'],['Deposit paid','Deposit','REAL']]}],
 marking:['Each complete row earns one mark, four overall. The teacher names are examples; other meaningful names with the correct types are valid.'],
 mistakes:['CHAR holds one character, not the whole customer name. INTEGER cannot retain the fractional part of the deposit.']},
 E070:{title:'Identify the constructs needed by a stated algorithm',commandWord:'Identify',
 reading:['Sequence is already supplied. Identify the two other constructs needed to process all inputs and choose which values enter the total.'],
 solution:['Iteration, using a count-controlled loop for the 100 inputs. Selection, using a condition to decide whether each input lies between 30 and 70 inclusive.'],
 marking:['There is one mark for iteration and one for selection. The descriptions explain the choices but do not create extra marks.'],
 mistakes:['A variable or an operator is not a programming construct. The final output happens after all 100 inputs, not after the first accepted number.']},
 E071:{title:'Draw an algorithm with two stopping conditions',commandWord:'Draw',
 reading:['The first 27 starts collection and is not added. Before it, even 0 is ignored. After it, 0 stops collection; a later 27 is ordinary data and must be added.'],
 solution:[{type:'diagram',name:'sentinel-flow'}, 'The first loop consumes values until 27. A separate loop then inputs and adds values until 0. For the teacher test sequence 0, 5, 27, 4, 27, 0, the total is 31: only 4 and the second 27 contribute.'],
 marking:['The five points cover initialisation, waiting for the first 27, the ending 0 loop, summing after the first 27, and output after a reasonable attempt. The official flowchart gives a complete accepted drawing.'],
 mistakes:['One loop that stops at any 0 can terminate before collection starts. Adding the first 27 changes the specified result. Make each decision branch and return arrow explicit.']},
 E072:{title:'Refine a fixed-input algorithm in words',commandWord:'Outline',
 reading:['The answer must have five steps in words, not pseudocode statements. Include both boundaries and produce one output after all inputs.'],
 solution:['1. Set the running total to zero.', '2. Input the next number.', '3. If this number is at least 30 and at most 70, add it to the running total.', '4. Repeat steps 2 and 3 until exactly 100 numbers have been input.', '5. Output the final total.'],
 marking:['The official scheme lists six marking points but caps the result at five. The third step combines the condition and addition. The paper says numbers; use inclusive comparisons so fractional numbers near the boundaries are handled correctly, rather than relying on an integer-only shortcut.'],
 mistakes:['“Repeat 100 times” after processing one input can imply 101 inputs. “Between” without stating inclusive endpoints can obscure whether 30 and 70 are accepted.']},
 E073:{title:'Diagnose a bonus flowchart',commandWord:'Explain',
 reading:['Trace a value from the failing range through the actual arrows. Then change the decisions while preserving the pay bands in the table.'],
 solution:['2(a)(i): For a value from 2000 to 4000, the first test ValueOfSales > 4000 is false, so the path bypasses the second decision and returns the initial bonus of 0.', '2(a)(ii): Swap the two decision tests. First test ValueOfSales >= 2000; on its YES path test ValueOfSales > 4000. This gives 0 below 2000, 10 from 2000 through 4000, and 100 above 4000.'],
 marking:['Each subpart has one mark. The scheme accepts identifying the wrong first decision for (i) and swapping the two decision boxes or specifying both corrected tests for (ii).'],
 mistakes:['Changing > 4000 to >= 4000 alone does not repair the middle band. Check 1999, 2000, 4000 and 4001 after the change.']},
 E074:{title:'Refine a banded points calculation',commandWord:'Apply',
 reading:['Choose the band using the amount spent, then use whole dollars to calculate points. The rate applies to the whole eligible amount, not progressively to separate portions.'],
 solution:['1. Read the amount spent into a numeric variable.', '2. Use a rate of 5 points per dollar if the amount is below 10; otherwise use 7 if the amount is at most 100, or 10 if it is above 100.', '3. Discard the fractional dollar part of the amount to obtain the number of whole dollars.', '4. Multiply the whole-dollar amount by the selected rate to calculate the points.', '5. Output the number of points.', 'For the supplied example 99.77, choose rate 7, use 99 whole dollars and obtain 693 points. A teacher boundary check at 100.50 uses rate 10 and 100 whole dollars, giving 1000 points.'],
 marking:['The scheme offers six possible points with a maximum of five. It recognises selecting one band and selecting all bands separately. The phrase “rounded value” in the scheme must be read alongside the question’s whole-dollar rule: the example requires discarding the fractional part, not rounding to the nearest dollar.'],
 mistakes:['Truncating 100.50 before choosing its band would select the wrong rate. Applying 5 to the first 10 dollars and 7 to the next portion invents progressive bands.']}
};
