export default {
 E098:{title:'Choose a development model for changing requirements',commandWord:'Give / Identify',
 reading:['Use both pressures in the scenario: reach the market early and respond as console features become known.'],
 solution:['5(a)(i): A waterfall approach may not produce working software until late, so a competitor may demonstrate the console first. It also makes changing requirements harder to accommodate after earlier stages have been completed.', '5(a)(ii): An iterative model or Rapid Application Development (RAD) is more appropriate.'],
 marking:['Part (i) gives one mark for each of two accepted reasons. Part (ii) gives one for an accepted alternative. An unsupported claim that waterfall is always unsuitable does not use the scenario.'],
 mistakes:['A model choice is justified by project conditions. Do not claim that waterfall never permits any feedback; explain the difficulty and delay when requirements change.']},
 E099:{title:'Complete a structure chart from module interfaces',commandWord:'Complete / Explain',
 reading:['Use the headers to label data and control transfers. Reset has a reference parameter, so its value can travel back to its caller; functions return values too.'],
 solution:[{type:'diagram',name:'module-structure'}, {type:'table',headers:['Connection','Transfers'],rows:[['Module-A → Module-X','T1 (INTEGER) and S2 (REAL)'],['Module-X ↔ Reset','Code (INTEGER), passed by reference'],['Module-A → Module-Z','SA (INTEGER)'],['Module-Z → Module-A','INTEGER return'],['Module-A → Module-Y','RA (INTEGER) and RB (BOOLEAN)'],['Module-Y → Restore','OldCode (INTEGER)'],['Restore → Module-Y','BOOLEAN return'],['Module-Y → Module-A','BOOLEAN return']]}, '7(b): The diamond means selection. Module-A calls one of Module-X, Module-Y or Module-Z according to the decision made at run time.'],
 marking:['Part (a) awards four grouped points: names; Module-X/Reset transfers; Module-Z input and return; and Module-Y/Restore transfers and returns. Part (b) gives one point for selection and one for correctly naming the four modules.'],
 mistakes:['A Boolean is a control couple, shown with a filled circle in the original chart. An integer or real value uses an unfilled data-couple circle. The diamond here is not a flowchart box containing a written condition.']},
 E100:{title:'Complete a PIN state-transition diagram',commandWord:'Complete',
 reading:['Copy each table row into a directed transition. A repeated state means a self-loop. Keep the input before the separator and the output after it.'],
 solution:[{type:'diagram',name:'pin-states'}, {type:'table',headers:['From → To','Input | Output'],rows:[['S1 → S2','Input PIN'],['S2 → S2','Re-input PIN | Display error'],['S2 → S1','Cancel | Re-prompt'],['S2 → S4','Valid PIN | Enable payment'],['S2 → S3','Too many tries | Block Account']]}],
 marking:['The four marks cover the missing S1-to-S2 transition, the S2 loop label, S3 with its incoming label, and S4 with its incoming label. The already supplied cancel transition remains part of the complete diagram.'],
 mistakes:['“Too many tries” belongs on the arrow, not as the name of a new state. Re-input keeps the system in S2; it does not return to S1.']},
 E101:{title:'Separate syntax, bounds and unreachable-code errors',commandWord:'Identify / Explain',
 reading:['Find the requested two syntax errors and one other error in the actual code. Then explain why the redundant branch cannot be selected.'],
 solution:[{type:'table',headers:['5(a)(i): error','Correction'],rows:[['NEXT Index closes a WHILE loop','Use ENDWHILE.'],['The final & concatenates an INTEGER with strings','Convert Index with NUM_TO_STR(Index), or use OUTPUT arguments separated by commas.'],['INPUT Data[Index] accesses index 0','Remove this input statement: Process initialises the array from Label, and its valid indices are 1 to 200.']]}, '5(a)(ii): The OTHERWISE statement is unnecessary because Index MOD 2 can only produce 0 or 1 for these indices, and both cases are already present.', '5(b): A run-time error.'],
 marking:['Part (a)(i) gives one mark per identified error. The original scheme categorises the concatenation problem as syntax; retain that classification for this paper. Part (a)(ii) gives one for the statement and one for the reason. Part (b) is one mark.'],
 mistakes:['Changing Index to 1 at initialisation without adjusting the later increment skips Data[1]. Removing the inappropriate input preserves the intended loop from indices 1 to 200.']},
 E102:{title:'Explain stubs and an error detected by black-box testing',commandWord:'Describe / Identify',
 reading:['A stub temporarily stands in for an unfinished called module. The completed program already compiles, so the later test is about behaviour during execution.'],
 solution:['2(b)(ii): Replace unfinished modules with simple temporary modules that use the required interfaces. A stub can return an expected value or display a message to show that the calling program reached it.', '2(b)(iii): A logic error: the program runs but gives a result different from the specified result, for example a wrong bonus for a valid hours-and-sales combination.'],
 marking:['Part (ii) gives two points for replacement modules and their simple response. Part (iii) gives one for the error type and one for its matching description. A run-time error with a suitable description is an official alternative.'],
 mistakes:['A stub is not a complete implementation of the missing calculation. Passing one black-box test does not show that all internal paths have been exercised.']},
 E103:{title:'Identify the customer’s final testing stage',commandWord:'Identify',
 reading:['Alpha and beta testing are explicitly finished. The customer now checks the completed system against their requirements.'],
 solution:['Acceptance testing.'],
 marking:['This is a one-mark identification question; a long description is not needed.'],
 mistakes:['Do not repeat beta testing when the question says it has already been completed.']},
 E104:{title:'Choose sensor tests within the stated input domain',commandWord:'Complete',
 reading:['The sensor produces non-negative integers only. Include the accepted endpoints and an attainable value above the maximum; supply type, value and outcome for every row.'],
 solution:[{type:'table',headers:['Type','Value','Expected outcome'],rows:[['Boundary/extreme','0','Data item is accepted'],['Boundary/extreme','60','Data item is accepted'],['Abnormal','61','Data item is rejected'],['Normal','15','Data item is accepted']]}],
 marking:['One mark is available for each completed row containing all three fields, four overall. The official scheme also permits some nearby accepted values and type labels. The table above uses the exact valid endpoints.'],
 mistakes:['−1 cannot be generated under the stated sensor constraint. A fractional value does not belong to the specified integer input domain. Valid boundary data is accepted; “boundary” does not mean invalid.']},
 E105:{title:'Design distinct valid test sequences',commandWord:'Give',
 reading:['Every sequence must satisfy the positive-integer input requirement and end with 99. Test different behaviours instead of submitting three mixed lists like the example.'],
 solution:[{type:'table',headers:['Sequence','Purpose','Expected counts (odd, even)'],rows:[['1, 3, 5, 99','Only odd data; the sentinel must not be counted','3, 0'],['2, 4, 6, 99','Only even data; the odd count must remain zero','0, 3'],['99','Immediate termination with no data values','0, 0']]}],
 marking:['The official rule is one mark per set including its stated purpose, to three. Although the scheme lists a missing-99 sequence as another example, the question asks for valid data. These three teacher sequences satisfy the written restriction and the listed scoring examples without that conflict.'],
 mistakes:['Counting 99 as an odd value gives every result an extra odd count. Three differently numbered mixed lists may test the same behaviour rather than three distinct aspects.']},
 E106:{title:'Explain why a working program needs adaptation',commandWord:'Give',
 reading:['Adaptive maintenance responds to changes around the program. Give three reasons applicable to controlling this factory’s production line.'],
 solution:['The production-line requirements change. New control hardware or technology replaces equipment used by the program. A library module used by the program changes its interface or required behaviour.'],
 marking:['There is one mark for each accepted reason, to three. A change in relevant legislation is another official option.'],
 mistakes:['Repairing an existing defect is corrective maintenance. Improving efficiency without an external change is normally perfective maintenance.']},
 E107:{title:'Redesign a record format when separators can occur in data',commandWord:'Explain',
 reading:['The encrypted fields may contain any separator you choose. Their maximum length of 99 makes a fixed two-digit length prefix sufficient for each field. Preserve one physical record line as required.'],
 solution:['Add a separator after the original email field to identify where the new section begins. Calculate the length of each encrypted item and write it as a fixed-width two-digit decimal string immediately before that item. Read the first two digits, then exactly that many characters, then repeat for the next item.', {type:'code',text:'Teacher example with invented encrypted data:\nAB1234\\Freddie Jones\\FreddieJ909@Cambridge.org\\03A\\B02xy'}, 'After the email separator, 03 means read the next three characters A, backslash, B. The following 02 means read x and y. The embedded backslash is data because the length determines the boundary. If “any character” includes a line break, encode it before writing and measure the encoded representation consistently so the record remains on one line; the printed examples use visible characters.'],
 marking:['The scheme lists four points with a maximum of three: boundary after the third original field, length calculation, stored lengths, and a fixed-width or separated representation of the lengths.'],
 mistakes:['Picking a different delimiter does not solve “any character”. An unseparated variable-width length is itself ambiguous. Document whether lengths describe the stored representation or decoded data.']}
};
