export default {
 E051:{title:'Explain professional membership',commandWord:'Explain',
 reading:['Give reasons for a programmer to join a professional ethical body. Connect the support or standards to the programmer’s work.'],
 solution:['The body supplies ethical guidelines so the programmer and clients know the standards expected of the work. It can provide training that keeps the programmer’s skills up to date. It can also offer professional support, including advice when ethical problems arise.'],
 marking:['The maximum is three, with one mark for each accepted point. The scheme also accepts reputation, entry requirements, recognition and legal advice; naming several bodies earns no extra credit.'],
 mistakes:['“It is good for programmers” does not identify a benefit. A professional body is not the same as the programmer’s employer.']},
 E052:{title:'State the purpose of a code of conduct',commandWord:'Describe',
 reading:['Describe what the code establishes. You do not need to invent a disciplinary case or list an organisation’s rules.'],
 solution:['A code of conduct sets out the behaviour and professional standards expected of members. It also explains the consequences of failing to follow those standards.'],
 marking:['Two accepted purpose statements earn the two available marks. The scheme also accepts promoting safe professional work, good practice and public trust.'],
 mistakes:['A code of conduct guides professional behaviour; program source code instructs a computer.']},
 E053:{title:'Apply ethical responsibilities to two groups',commandWord:'Explain',
 reading:['Address colleagues and the public separately. A long answer about only one group is capped at two marks.'],
 solution:['Towards colleagues, the programmer should give constructive criticism so that their colleagues can improve their work. Towards the public, the programmer should be honest and realistic about what the software can do so that the public can trust the claims made about it.'],
 marking:['The scheme allows at most two marks for colleagues and two for the public. Each sentence gives an action and its consequence. Other accepted actions include fair treatment, giving credit and protecting public health or personal information.'],
 mistakes:['A general statement such as “be ethical to everyone” does not show how the responsibility applies to either group.']},
 E054:{title:'Choose a software licence and explain copyright',commandWord:'Identify / Explain',
 reading:['The business can modify source code and pay for continuing maintenance. Consider both conditions: payment does not automatically mean closed source. Then answer the separate copyright question.'],
 solution:['5(b)(i): An open-source/free-software licence is suitable: it permits access to and modification of source code, while the programmer can charge for maintenance or updates.', '5(b)(ii): Copyright identifies the programmer’s ownership of the work and provides a basis for action against copying or distribution that breaches the permitted terms.'],
 marking:['Part (i) awards one mark for the licence category and up to two for reasons. The official scheme uses “Open Source Initiative // Free Software Foundation” for its licence answer. Those are organisation names, not names of individual licences; the intended category permits source access and modification. Part (ii) has a separate two-mark cap.'],
 mistakes:['Free software does not necessarily mean no money can be charged. Copyright and an open licence can coexist: the licence states what the copyright holder permits.']},
 E055:{title:'Explain an AI reading and translation device',commandWord:'Explain / State',
 reading:['Follow the product’s sequence: camera image, recognised words, translation, spoken output. For social benefits, identify people helped and what they can do more easily.'],
 solution:['3(a): Optical character recognition locates characters in the camera image and converts their pixel patterns into text. Natural language processing combines the recognised words into meaningful phrases and interprets their context. A translation system produces the corresponding words in the chosen language. Text-to-speech turns the translated text into an audio waveform that the user hears.', '3(b): A visually impaired shopper can hear product information that they cannot read on the label. A shopper who does not understand the label’s language can hear the information in a language they understand.'],
 marking:['Part (a) has a maximum of four marks across the accepted stages and details. Part (b) allows two social benefits; do not spend both statements repeating the same accessibility benefit.'],
 mistakes:['“AI reads it” names no process. Recognising the characters and translating their meaning are different stages. Speed alone needs a clear social benefit in this situation.']}
};
