export default {
 E075:{title:'Read literal notation before choosing a type',commandWord:'Complete',
 reading:['Classify the values as written in pseudocode. Quotation marks are part of the type evidence, even when the text resembles a date.'],
 solution:[{type:'table',headers:['Variable','Type','Reason'],rows:[['Available','BOOLEAN','TRUE is a Boolean literal.'],['Received','STRING','The date-shaped value is enclosed in double quotation marks.'],['Index','INTEGER','100 is a whole-number value.']]}],
 marking:['One mark per correct row, three overall. The reasons explain the decisions; the original table asks only for the types.'],
 mistakes:['Do not answer DATE just because the characters represent a calendar date. Read the literal notation supplied.']},
 E076:{title:'Declare a mixed-type record',commandWord:'Write',
 reading:['Use the exact type and field names. Item_Num is used as an array index, Stage is one letter, and either limit may contain a fraction.'],
 solution:[{type:'code',text:'TYPE Component\n    DECLARE Item_Num : INTEGER\n    DECLARE Reject : BOOLEAN\n    DECLARE Stage : CHAR\n    DECLARE Limit_1 : REAL\n    DECLARE Limit_2 : REAL\nENDTYPE'}, 'A record groups related fields of different types under one record type. This declaration describes the structure; it does not allocate the later array of items.'],
 marking:['Four grouped marks cover the TYPE/ENDTYPE pair, Item_Num with Reject, Stage, and both REAL limit fields. Five fields do not mean five marks.'],
 mistakes:['An identifier that happens to contain digits may normally be text, but this question explicitly says it is used as a numeric array index. Do not omit either limit.']},
 E077:{title:'Count array elements using inclusive bounds',commandWord:'State / Give',
 reading:['Both dimensions start at zero. Count allowed index values, not the number printed as the upper bound.'],
 solution:['1(d)(i): Two dimensions.', '1(d)(ii): (99 − 0 + 1) × (9 − 0 + 1) = 100 × 10 = 1000 elements.', {type:'code',text:'DECLARE Product : ARRAY[0:99, 0:9] OF INTEGER'}],
 marking:['The first two answers earn one mark each. The declaration has one mark for both correct ranges and one for the remaining declaration syntax and INTEGER type.'],
 mistakes:['99 × 9 omits the zero-indexed row and column. Replacing the ranges with 1:100 and 1:10 changes the required indexing even though the element count is the same.']},
 E078:{title:'Store inputs and output them in reverse',commandWord:'Complete',
 reading:['Store all 100 inputs before the output phase. The question does not request array declarations. Use a count-controlled traversal in each direction.'],
 solution:[{type:'diagram',name:'reverse-array-flow'}, 'The input phase uses Number[1] through Number[100] once each. After it finishes, reset Index to 100. The output phase visits 100, 99, …, 1. The data stays in its original array positions; reverse traversal produces the reversed output order.'],
 marking:['The scheme lists seven functional groups with a maximum of six marks. Its accepted starting indices include 0 or 1, provided the 100-element input and complete reverse output are consistent.'],
 mistakes:['After a 1-based input loop, Index is 101: decrement or reset it before accessing Number again. Reversing each input immediately cannot reverse the entire sequence.']},
 E079:{title:'Combine a row condition with two column matches',commandWord:'Write',
 reading:['Row and Search are already available. Test the current row; do not write a new complete search function. MOD gives the remainder, so an even row has remainder zero on division by two.'],
 solution:[{type:'code',text:'IF (Row MOD 2 = 0) AND\n   ((Data[Row, 1] = Search) OR (Data[Row, 2] = Search)) THEN\n    // Both required conditions are satisfied\nENDIF'}, 'The two equality tests form one OR group. The AND applies the even-row restriction to that entire group. A row with the search string in both columns satisfies the condition once, not twice.'],
 marking:['The three points are the even-row test, a match in either column, and a correctly combined selection structure. The official alternatives include nested selection. The comment here identifies where the counting action belongs; no counting statement is requested.'],
 mistakes:['Using AND between the column tests demands both matches. Omitting the parentheses around OR can let an odd row pass when column 2 matches.']},
 E080:{title:'Convert three-line records to one-line records',commandWord:'Complete / Explain',
 reading:['Each valid old record consists of exactly three lines. Keep their order and put separators between fields, not between whole records.'],
 solution:['Step 1: Open OldFile.txt in READ mode.', 'Step 2: Open NewFile.txt in WRITE mode.', 'Step 3: Read a line from OldFile.txt into LineX.', 'Step 4: Read the next line into LineY.', 'Step 5: Read the next line into LineZ.', {type:'code',text:"Step 6: Set NewString to LineX & '\\' & LineY & '\\' & LineZ"}, 'Step 7: Write NewString as one line in NewFile.txt.', 'Step 8: Repeat from step 3 until the end of OldFile.txt.', 'Step 9: Close both files.', '3(b): The separator is suitable because it does not appear in the information items in this file design.'],
 marking:['Part (a) has six marks for the missing operations, not one mark for each of nine steps. The given READ steps and closing step still matter to the complete algorithm. Part (b) gives one mark for distinguishing the separator from the data.'],
 mistakes:['Opening NewFile.txt in WRITE inside the loop can overwrite earlier records. This question assumes valid records; a production implementation would also check EOF before attempting to read the first record of an empty file.']},
 E081:{title:'Represent a stack and describe a push',commandWord:'Complete',
 reading:['The top pointer identifies the last occupied element. The array fills from its lowest index, and all eight positions are usable.'],
 solution:[{type:'table',headers:['Index','Data'],rows:[['8','unused'],['7','unused'],['6','unused'],['5','D1'],['4','D3'],['3','D4'],['2','D5'],['1','D2']]}, '3(a): TopOfStack = 5; BottomOfStack = 1.', '3(b), step 1: If TopOfStack = 8, return FALSE because the stack is full.', 'Step 2: Otherwise increment TopOfStack.', 'Step 3: Use TopOfStack as the array index.', 'Step 4: Store the new value in that array element.', 'Step 5: Return TRUE.'],
 marking:['Part (a) has one mark for all data positions and one for each pointer. Part (b) gives one mark per completed step, five in total.'],
 mistakes:['Storing before incrementing overwrites the old top in this convention. Do not import a different convention in which the top pointer indicates the next free location.']},
 E082:{title:'Trace a circular queue across its last location',commandWord:'Describe / State',
 reading:['Here End points to the last item added. After index 9 comes index 0. In part (ii), stored values outside the active pointer interval may be old data.'],
 solution:[{type:'table',headers:['Operation','Front','End','Write'],rows:[['Initial state','5','8','—'],['Check space; add Orange','5','9','Orange at index 9'],['Check space; add Yellow','5','0','Yellow at index 0']]}, '3(a)(ii): Seven items. Follow the active queue from Front = 5 through indices 5, 6, 7, 8, 9, 0 and 1, ending at End = 1. Locations 2, 3 and 4 are outside this active queue despite still containing old values.'],
 marking:['Part (i) lists five possible points with a four-mark cap: capacity check, two pointer movements and two corresponding writes. Part (ii) is one mark for seven.'],
 mistakes:['End − Front + 1 fails when the queue wraps. Counting all ten nonblank cells confuses stored remnants with active items.']},
 E083:{title:'Insert a node while preserving both lists',commandWord:'Complete',
 reading:['Use the first free node F1 and insert it between D32 and D11. Preserve the remaining free list as well as the active list.'],
 solution:['Step 1: Store D6 in the node currently labelled F1.', 'Step 2: Set that node’s pointer to the node containing D11.', 'Step 3: Set Ptr2 to the node containing F2.', 'Step 4: Set the pointer of D32 to the new D6 node.', 'The resulting active chain is D40 → D32 → D6 → D11 → D100 → null. The remaining free chain begins at F2. When implementing these steps, retain access to F2 before overwriting F1’s old link.'],
 marking:['There is one mark per completed step. The official answer labels nodes by their data; the pointer values in an implementation refer to locations, not the text “D6”.'],
 mistakes:['Overwriting D32’s link before saving access to D11 can lose the remainder of the list. F1 must also be removed from the free list.']},
 E084:{title:'Translate a linked-list diagram into arrays',commandWord:'Complete',
 reading:['Follow the logical chain rather than the physical order of array rows. Each pointer contains the index of the next node.'],
 solution:[{type:'table',headers:['Index','Data','Pointer'],rows:[['1','D32','2'],['2','D11','3'],['3','D100','0'],['4','D40','1'],['5','F1','6'],['6','F2','7'],['7','F3','8'],['8','F4','0']]}, 'Start_Pointer = 4; Free_List_Pointer = 5. The active chain follows 4 → 1 → 2 → 3 → 0, while the free chain follows 5 → 6 → 7 → 8 → 0.'],
 marking:['The five marking groups are the start pointer, row 2, rows 3 and 4 together, row 5, and rows 7 and 8 together. The diagram’s outlined groups preserve these limits. The scheme accepts null as 0, ∅ or another out-of-bounds index.'],
 mistakes:['Data and pointer values have different meanings. A pointer to the next array row is only correct when that row contains the next logical node.']},
 E085:{title:'Reverse a stack through a queue',commandWord:'Describe',
 reading:['The number of items is unknown. Continue each phase until its source is empty. Here the queue’s rear pointer indicates the next insertion location, unlike the earlier circular-queue question.'],
 solution:['Phase 1: While the stack is not empty, read the item at its top pointer and move that pointer to the next occupied stack location. Store the removed item at the queue’s rear pointer and advance the rear pointer to the next insertion location.', 'Phase 2: While the queue is not empty, read the item at its front pointer and advance that pointer. Move the stack’s top pointer to its next free stack location and store the removed queue item there.', {type:'table',headers:['Stage','Order'],rows:[['Popped from original stack','6, 5, 4, 3, 2, 1'],['Removed from queue','6, 5, 4, 3, 2, 1'],['Final stack, bottom to top','6, 5, 4, 3, 2, 1']]}],
 marking:['The official list contains ten operational points but the total is capped at seven. Explain both transfers, pointer updates and stopping conditions. A six-iteration loop does not handle the stated unknown stack size.'],
 mistakes:['A second stack would reverse the order at a different stage. FIFO removal preserves the pop sequence as items are pushed back, making item 1 the new top.']}
};
