export default {
 E029:{title:'State what each register holds',commandWord:'Complete / Describe',
 reading:['Describe the purpose of each named register. Distinguish an address, the contents at an address, and an offset.'],
 solution:[{type:'table',headers:['Register','Purpose'],rows:[['PC','Holds the address of the next instruction to fetch.'],['MAR','Holds the address of the memory location being read or written.'],['MDR','Holds the data/instruction read from the location addressed by MAR, or the data to write there.'],['IX','Holds an offset added to an instruction’s operand to form the effective address in indexed addressing.']]}],
 marking:['One mark is awarded for each correct purpose. Describing a register only as “temporary storage” does not distinguish its role.'],
 mistakes:['MAR holds an address; MDR holds the transferred contents. PC holds the next instruction’s address, not the instruction itself.']},
 E030:{title:'Use the monitor’s resolution and speakers in an explanation',commandWord:'Explain',
 reading:['The monitor has 2560 × 1600 pixels and built-in speakers. Link interface features to these given requirements.'],
 solution:['HDMI can carry both the video and the audio for the built-in speakers, so a separate audio cable is not needed as it would be with VGA. It supports the monitor’s high-resolution image and transfers a digital signal, avoiding conversion of the image to analogue and back.'],
 marking:['The scheme awards up to four listed benefits or linked consequences. The answer supplies combined audio/video, no separate sound cable, high-resolution support and the digital-signal benefit. Additional acceptable points do not raise the total.'],
 mistakes:['“HDMI is better” is not a mechanism. Do not invent a transfer-rate multiplier or claim that every HDMI/VGA version has the same maximum resolution.']},
 E031:{title:'Explain two separate processor improvements',commandWord:'Explain',
 reading:['Both processors are dual-core: the number of cores has not increased. Explain the clock-speed and cache changes separately.'],
 solution:['The higher clock speed permits more fetch-execute cycles per second, so more instructions can be processed in a given time.', 'The larger cache can hold more frequently used instructions close to the processor. More accesses can therefore be served from cache instead of slower RAM, reducing waiting time.'],
 marking:['The four marks are capped at two for clock speed and two for cache. A detailed answer about only one factor cannot earn all four.'],
 mistakes:['The cache capacity doubles, but that does not establish that total computer performance doubles. Neither change adds processor cores.']},
 E032:{title:'Translate descriptions into register-transfer notation',commandWord:'Complete',
 reading:['An arrow means assignment. Square brackets mean contents, so reading memory via an address held in MAR needs two levels of contents.'],
 solution:[{type:'table',headers:['Stage','Register-transfer notation'],rows:[['Increment PC','PC ← [PC] + 1'],['Read the memory location addressed by MAR into MDR','MDR ← [[MAR]]']]},'The inner [MAR] is the stored address. The outer brackets mean the contents of memory at that address.'],
 marking:['Each correctly written transfer earns one mark. The second notation expresses a memory read rather than copying the address itself.'],
 mistakes:['MDR ← [MAR] copies the address value, not the memory contents requested. PC ← 1 overwrites the counter instead of incrementing it.']},
 E033:{title:'Explain MAR and MDR through instruction fetch',commandWord:'Describe',
 reading:['Connect the two registers to the fetch-execute sequence. Give the source of the address and the destination of the fetched instruction.'],
 solution:['MAR holds the address of the memory location to be read or written. During instruction fetch it receives the next instruction address from PC. The instruction at that memory address is read into MDR. It then passes from MDR to CIR for decoding and execution. When executing a data read/write, MAR and MDR carry the required operand address and transferred value.'],
 marking:['The four listed points are the MAR role, the address from PC, the MDR role and passing the instruction to CIR. The final sentence distinguishes operand access from instruction fetch; it does not add marks.'],
 mistakes:['Do not say that the operand address always comes from PC: the PC supplies the instruction address during fetch. MDR does not select a memory location.']},
 E034:{title:'Explain interrupt detection, service and return',commandWord:'Explain',
 reading:['Include both detection at a cycle boundary and the handling sequence. Saving context has a purpose: the interrupted program must resume correctly.'],
 solution:['At the start or end of the fetch-execute cycle, the processor checks the interrupt register for pending requests and their priorities. If a request is to be serviced at a higher priority than the current process, the current register contents are saved on the stack. The appropriate interrupt service routine handles the device request. After it finishes, pending higher-priority requests are checked; when none requires service first, the saved registers are restored and the interrupted program continues with its next fetch-execute cycle.'],
 marking:['The official scheme lists several points but caps the answer at four marks. A complete explanation may include more than four connected steps; those steps are not four extra marks. It accepts the stated start/end cycle-boundary check.'],
 mistakes:['Jumping to an ISR without saving the program state can destroy values needed on return. “Start the program again” is different from resuming its saved state.']},
 E035:{title:'Read a many-to-many assembler matching task',commandWord:'Draw',
 reading:['“One or more lines” permits an action to connect to both passes. Decide for every action; do not assume three marks means exactly three lines.'],
 solution:[{type:'table',headers:['Action','Connect to'],rows:[['Generates object code','Second pass'],['Reads source code one line at a time','First and second passes'],['Removes white space','First pass'],['Adds labels to the symbol table','First pass']]},'Pass one reads the source and builds the symbol information needed to resolve label references. Pass two reads the source again and uses that information when producing object code. The official drawing below shows all five connections.'],
 marking:['The three scoring groups are: object code to the second pass; line-by-line reading to both passes; both white-space removal and symbol-table labels to the first pass. The final two actions form one scoring group.'],
 mistakes:['Connecting source reading to just one pass does not satisfy its group. Counting drawn lines is not the marking rule.']},
 E036:{title:'Trace an indexed loop with character input and output',commandWord:'Trace',
 reading:['Input is the character “1”, whose supplied ASCII value is 49. Follow executed addresses, including the second visit to 13–15. The comparison does not change ACC.'],
 solution:[
 'LDR sets IX to 0. IN places 49 in ACC, and STO 101 saves it. The first indexed load reads location 110 + 0 = 110, giving 51. This does not equal Memory[100]=0, so JPE is not taken. The program reloads 49, adds 16 to obtain 65, increments IX to 1 and stores 65 in location 100.',
 'On the second visit, LDX reads location 111 and gets 65. It now equals Memory[100], so JPE goes to 21. OUT emits the character with ASCII code 65, which is A, and END returns control to the operating system.',
 {type:'table',headers:['Executed address','ACC after','IX after','Memory[100]','Memory[101]','Output'],rows:[['10','Unchanged; initial value not supplied',0,0,0,'—'],['11',49,0,0,0,'—'],['12',49,0,0,49,'—'],['13',51,0,0,49,'—'],['14',51,0,0,49,'—'],['15',51,0,0,49,'—'],['16',49,0,0,49,'—'],['17',65,0,0,49,'—'],['18',65,1,0,49,'—'],['19',65,1,65,49,'—'],['20',65,1,65,49,'—'],['13',65,1,65,49,'—'],['14',65,1,65,49,'—'],['15',65,1,65,49,'—'],['21',65,1,65,49,'A'],['22',65,1,65,49,'—']]},
 'Memory[110]=51 and Memory[111]=65 throughout. The teacher table carries unchanged values forward to make state changes visible; the official table below records changes in the supplied answer layout.'
 ],
 marking:['The official answer awards one mark for each of four groups of rows, identified by its bands: addresses 10–12; first 13–16; 17–20; then the second 13–15 and 21–22. It does not give a mark for each instruction or each filled cell. Keep the complete grouped official table when checking the trace.'],
 mistakes:['Using numeric 1 instead of ASCII 49 changes the calculation. Forgetting the new IX makes the second LDX read the wrong cell. OUT prints A, not the digits 65.']},
 E037:{title:'Distinguish direct and immediate bitwise operands',commandWord:'Complete',
 reading:['ACC is reloaded to 01000110 before each program. Plain 29 is an address; #29 is the denary value 29.'],
 solution:[{type:'table',headers:['Program','Operand actually used','Calculation','ACC'],rows:[['XOR 29','Memory[29] = 00001111','01000110 XOR 00001111','01001001'],['AND #29','29 = 00011101','01000110 AND 00011101','00000100'],['OR B11111111','11111111','01000110 OR 11111111','11111111']]}],
 marking:['One mark is awarded for each correct ACC result. Intermediate conversions help avoid operand errors but do not create extra marks.'],
 mistakes:['Do not chain the three results: each program starts with the supplied original ACC. AND #29 does not read Memory[29].']},
 E038:{title:'Write a bitwise odd-number test',commandWord:'Explain / Write',
 reading:['The required result is a test of the stored integer’s oddness. Isolate only the least significant bit and then interpret the result.'],
 solution:['All binary place values except the least significant one are even. An odd integer therefore has a least significant bit of 1. AND with 00000001 clears every other bit and preserves that bit.', {type:'code',text:'AND B00000001'}, 'Compare the resulting ACC with denary 1: equality means the original number was odd. The supplied example 10011010 would produce 00000000, so that example is even. AND #1 and AND &01 are equivalent immediate forms allowed by this scheme.'],
 marking:['The explanation is capped at two marks, and the correct masking instruction earns one separate mark. A suitable instruction alone does not explain why it tests oddness.'],
 mistakes:['AND 1 uses direct addressing and is not the same as AND #1. Masking changes ACC, so preserve the original elsewhere first if a later program step still needs it.']}
};
