export default {
 E011:{title:'Assign client and server roles in a banking app',commandWord:'Describe',
 reading:['Identify the devices in this banking system before describing what each does. Give both ends of the request-response exchange.'],
 solution:['The bank’s central computer is the server. It receives account requests from customers’ devices, processes them using account data, and sends a response.', 'The customer’s smartphone running the banking application is a client. It sends the customer’s request, waits for the server’s response and displays the returned information.'],
 marking:['The four marks distinguish identifying the server, describing its role, identifying the client and describing its role. “A server serves clients” does not supply the banking application or the work performed.'],
 mistakes:['The phone does not become the server simply because it displays the balance. Identify where the request is processed and where the response is requested and shown.']},
 E012:{title:'Apply thin-client characteristics to exam marking',commandWord:'Complete / Describe',
 reading:['Each row requires a characteristic and its use or consequence in this marking software. Choose two different characteristics.'],
 solution:[{type:'table',headers:['Thin-client characteristic','Application to the marking software'],rows:[['Data is not stored permanently on the client','Digitised exam papers remain on the server rather than being permanently stored on the marker’s computer.'],['The client depends on access to the server','The marker cannot continue using the marking service if the server cannot be reached.']]}],
 marking:['Each row can earn one mark for the characteristic and one for the matching application. Two characteristics without the scenario-specific descriptions leave the application marks unsupported. The official scheme also accepts other matched pairs shown below.'],
 mistakes:['“Cheap” and “fast” alone do not state the thin-client mechanism. Do not contradict the shared stem: markers receive papers to work on, but this does not mean the thin client is their permanent store.']},
 E013:{title:'Follow a packet through a star topology',commandWord:'Explain',
 reading:['Describe the path between two devices, rather than just drawing the shape of a star. The central device must do something with the destination address.'],
 solution:['The sending device transmits the packet directly to the central switch. The switch checks the destination address and forwards the packet directly towards the intended receiving device.'],
 marking:['One mark covers sender-to-centre transmission; the other covers checking the destination and forwarding to the receiving device. The official answer allows a switch, router or central device. In a switched Ethernet LAN the switch uses the destination MAC address.'],
 mistakes:['Do not describe a chain through every workstation: that is not the stated star path. A central hub and a switch do not make identical forwarding decisions.']},
 E014:{title:'Give distinct benefits and drawbacks of cloud computing',commandWord:'Give',
 reading:['Keep the two benefits and two drawbacks separate. Give distinct points; restating “available anywhere” twice does not create a second benefit.'],
 solution:[{type:'table',headers:['Benefits','Drawbacks'],rows:[['Restaurant staff can access the same data from different internet-connected devices.','An internet outage can prevent access to the cloud service.'],['Storage capacity can be increased when the restaurant needs more space.','Provider downtime can make the data or software unavailable.']]}],
 marking:['Each subpart awards up to two marks for distinct acceptable points. There are more alternatives in the official scheme than available marks. Backup is a conditional service feature; it is not safe to promise that every provider includes an adequate backup.'],
 mistakes:['Do not claim unlimited free capacity or uninterrupted availability. Separate failure of the restaurant’s connection from failure of the provider.']},
 E015:{title:'Match a transmission medium to its mechanism',commandWord:'Identify / Describe',
 reading:['The stem already supplies copper cable and asks for two other media. Name each medium and explain how it carries data.'],
 solution:[{type:'table',headers:['Transmission medium','Description'],rows:[['Fibre-optic cable','Represents data using pulses of light sent along the fibre.'],['Radio waves / microwaves','Carries data using electromagnetic waves at suitable radio or microwave frequencies.']]}],
 marking:['Each pair earns one mark for an appropriate medium and one for its matching description: two pairs, four marks maximum.'],
 mistakes:['Twisted pair and coaxial cable are still copper options. “Fast” describes possible performance, not the transmission mechanism requested in the description column.']},
 E016:{title:'Describe Ethernet beyond the cable',commandWord:'Describe',
 reading:['Ethernet is a communication standard/protocol family. Supply technical features of transmission, not merely a cable name.'],
 solution:['Ethernet is a protocol suite for transmitting data over standard wired network connections. It carries data in frames. Frames include source and destination addressing and error-checking information.'],
 marking:['The scheme awards up to three marks from its listed features. Protocol suite, standard wired connections and transmission in frames provide three distinct points. Its CSMA/CD alternative applies to shared half-duplex Ethernet; switched full-duplex links do not use collision detection to arbitrate normal traffic.'],
 mistakes:['Do not define all networking, Wi-Fi or internet access as Ethernet. In an Ethernet frame the link-layer source and destination are MAC addresses; do not teach the scheme’s broad IP/MAC wording as a rule that IP and MAC are interchangeable.']},
 E017:{title:'Sequence collision-handling tasks',commandWord:'State',
 reading:['The question asks for three tasks in CSMA/CD. Choose actions, and keep the order of detection, stopping and retrying coherent.'],
 solution:['Monitor the shared communication channel and transmit only when it is idle.', 'If a collision is detected, stop the data transmission and send a jamming signal.', 'Calculate a random back-off delay before attempting retransmission; check the channel again before sending.'],
 marking:['The scheme awards a maximum of three marks from the listed channel-monitoring, collision and retry actions. A sentence can contain more than one listed action; sentence count is not the marking rule.'],
 mistakes:['An identical fixed delay can make both devices collide again. Waiting does not grant permission to transmit into a busy channel.']},
 E018:{title:'Explain real-time audio and video streaming',commandWord:'Explain',
 reading:['Explain an ongoing conference, where playback must occur while more data arrives. Include the sending stream and the receiver’s buffer.'],
 solution:['Audio and video are compressed and sent continuously as a stream of bits to a media server. The server sends the incoming stream to the receiving device’s buffer. The buffer temporarily holds arriving data until it can be processed. The device reads buffered data to play the conference while later data is still arriving.'],
 marking:['The scheme awards up to four marks from compression, continuous bit transmission, the media server and the receiver’s buffer operations. The explanation connects those stages instead of repeating “it streams live”.'],
 mistakes:['Waiting for the entire conference file before playback would not meet the real-time requirement. A buffer absorbs variation; it does not fix a permanently insufficient average arrival rate.']},
 E019:{title:'Describe the PSTN’s role in internet transmission',commandWord:'Describe',
 reading:['This selected subpart asks about the telephone-network infrastructure, rather than the router question that precedes it in the paper.'],
 solution:['The PSTN includes different types of communication lines. Where a line requires another signal form, digital data must be converted appropriately, for example to an analogue signal on an analogue segment. Communication is passed through switching centres and service providers towards its destination.'],
 marking:['The scheme accepts up to two relevant points, including different line types, required conversion, duplex transmission and switching centres/ISPs. Two connected points are sufficient.'],
 mistakes:['Do not describe the whole modern PSTN as analogue. Conversion is required where the particular link demands it, not automatically on every segment.']},
 E020:{title:'Separate IP version, subnet purpose and address type',commandWord:'Explain / Describe / Complete',
 reading:['7(a) concerns the notation and size of the supplied address. In 7(b)(iii), separating logical segments is already stated: give two other purposes with explanations. In 7(d), public/private and static/dynamic classify different properties.'],
 solution:['7(a): 192.168.3.2 uses four denary groups separated by dots. This is IPv4 notation for a 32-bit address, rather than the colon-separated hexadecimal representation of a 128-bit IPv6 address.',
 {type:'table',headers:['7(b)(iii): purpose','Matching explanation'],rows:[['Reduce network congestion','Traffic between devices on the same subnet can remain within that subnet, reducing traffic reaching other segments.'],['Make faults easier to manage','The administrator can isolate a fault to a smaller logical segment and investigate its devices.']]},
 {type:'table',headers:['7(d): missing entry','Answer'],rows:[['Internet access address type','Public IP address'],['Static address description','An assigned address that remains fixed when the device rejoins the network.'],['Internal LAN address type','Private IP address'],['Dynamic address description','An assigned address that may change when the device rejoins the network.']]}],
 marking:['7(a): up to two distinguishing points. 7(b)(iii): up to two uses plus their corresponding expansions, four marks total. 7(d): one mark for each of the four missing entries. The fully written definitions in the official scheme include table text that was already supplied; only missing areas are scored.'],
 mistakes:['A private address can be static or dynamic. Repeating “logical segments” in 7(b)(iii) restates the given information. If using the security alternative, explain suitable segmentation/access controls; a subnet mask alone is not an access-control policy.']}
};
