export default {
 E056:{title:'Explain the move to a relational database',commandWord:'Explain',
 reading:['Explain benefits compared with separately maintained files. Use the repair company to make the effect of each benefit clear.'],
 solution:['A customer’s details can be stored once and referenced from their repair jobs, reducing repeated data. Updating that single customer record means that queries for their jobs use the same current details, improving consistency. Different views can show employees only the information needed for their work.'],
 marking:['The scheme accepts three points at most. Redundancy, consistency, independence, queries, views and concurrent access are alternatives, not a requirement to list everything.'],
 mistakes:['A relational database does not automatically copy every change into every table. In this example, jobs reference the same customer record; referential constraints and update rules govern changes to keys.']},
 E057:{title:'Design three related quiz tables',commandWord:'Create',
 reading:['Separate facts about a user, a quiz and one user’s attempt at a quiz. Use the unique username and identify every primary and foreign key.'],
 solution:[{type:'code',text:'USER(Username, Email, DateOfBirth, Rating)\n  Primary key: Username\nQUIZ(QuizID, Date, Filename)\n  Primary key: QuizID\nUSER_QUIZ(Username, QuizID, Score)\n  Primary key: (Username, QuizID)\n  Foreign key: Username references USER(Username)\n  Foreign key: QuizID references QUIZ(QuizID)'}, 'A score belongs to the pairing of a user and a quiz. Rating belongs to the user. The linking table therefore holds Score, while USER holds Rating. The combination in the linking table distinguishes different users attempting the same quiz and one user attempting different quizzes.'],
 marking:['The official list contains seven possible points but the question is worth six. The answer supplies the required tables, fields and keys; the maximum remains six. Date or filename can also identify QUIZ in the official scheme when the remaining required quiz fields are included.'],
 mistakes:['Putting Score in USER allows only one score per user. Merely listing three tables without primary keys or matching foreign keys leaves their relationships unclear.']},
 E058:{title:'Normalise the ice-cream batch table',commandWord:'Normalise / Identify',
 reading:['Use the repeated product facts in the sample rows. The question explicitly forbids changing CUSTOMER and SALE; only redesign BATCH and its new related table.'],
 solution:[{type:'code',text:'BATCH(BatchID, IceCreamID, EndDate)\n  Primary key: BatchID\n  Foreign key: IceCreamID references ICE_CREAM(IceCreamID)\nICE_CREAM(IceCreamID, Type, Flavour, Size, SellingPrice)\n  Primary key: IceCreamID'}, 'The same product can be made in several batches. Its type, flavour, size and selling price belong in ICE_CREAM; the batch’s identifier and end date remain in BATCH. Each batch references the appropriate product.'],
 marking:['The four marks cover the new product table, its product fields, a suitable primary key and the matching foreign key in BATCH. The official table definitions are labelled examples rather than a complete example answer: explicitly identifying the keys completes the response.'],
 mistakes:['EndDate is a batch fact. Moving it to ICE_CREAM would force all batches of the product to share one end date. Do not redesign the two excluded tables.']},
 E059:{title:'Distinguish two DBMS descriptions',commandWord:'Describe',
 reading:['Give a definition and useful detail for each term. Keep the two two-mark answers separate.'],
 solution:['A data dictionary stores metadata describing the database, such as field names, data types, keys and validation rules.', 'A logical schema is a conceptual, platform-independent design of the database, showing entities and their relationships before a physical implementation is chosen.'],
 marking:['There are at most two marks for data dictionary and two for logical schema. An example supports the relevant definition; a long list of field types does not earn the logical-schema marks.'],
 mistakes:['Actual quiz scores are data. The definition of the Score field is metadata. A logical schema is not a list of disk locations.']},
 E060:{title:'Explain a DBMS developer interface',commandWord:'Describe',
 reading:['Describe what a developer can construct or maintain using the interface, rather than how an ordinary user views one saved record.'],
 solution:['The interface lets a developer create or modify database tables and set up relationships between them. It can also be used to design data-entry forms with controls such as drop-down lists.'],
 marking:['Any two accepted purposes can earn the two marks. The official scheme also accepts reports, menus and inspecting data or metadata through queries.'],
 mistakes:['“It makes the database easy to use” is too general. Name the object or action the interface supports.']},
 E061:{title:'Create a table and add a foreign key',commandWord:'Write',
 reading:['Read the sample values before choosing types: ExamID contains leading zeros. Part (c) changes an existing table’s relationship, not the data stored in its rows.'],
 solution:[{type:'code',text:'CREATE TABLE EXAM(\n    ExamID VARCHAR(8) NOT NULL,\n    Subject VARCHAR(40),\n    Level INTEGER,\n    TotalMarks INTEGER,\n    PRIMARY KEY (ExamID)\n);\n\nALTER TABLE EXAM_QUESTION\nADD FOREIGN KEY (ExamID) REFERENCES EXAM(ExamID);'}, 'Text preserves an identifier such as 00956124. Level and TotalMarks are whole-number fields. The second statement makes ExamID in EXAM_QUESTION refer to the primary key of EXAM. The text lengths shown here are teacher choices sufficient for the supplied examples.'],
 marking:['Part (b): one mark for the CREATE structure, one for all fields with suitable types and separators, and one for the primary key. Part (c): one for altering EXAM_QUESTION and one for linking the correct keys.'],
 mistakes:['UPDATE changes row values; it does not add this foreign-key constraint. Linking ExamQuestionID to ExamID connects the wrong attributes.']},
 E062:{title:'Count scheduled performances for each show',commandWord:'Write',
 reading:['The result needs the show name and a named count, not one count for the entire theatre. The performance records identify shows through ShowID.'],
 solution:[{type:'code',text:'SELECT SHOW.Title, COUNT(PERFORMANCE.PerformanceID) AS NumberOfShowings\nFROM PERFORMANCE INNER JOIN SHOW\nON PERFORMANCE.ShowID = SHOW.ShowID\nGROUP BY SHOW.Title;'}, 'Join each performance to its show to obtain Title. Group those rows by Title, then count the performance identifiers inside each group. In the supplied sample MK12 has three performances and OP3 has three; their titles are obtained from SHOW, whose rows are not supplied, so do not invent titles as official output.'],
 marking:['The four marks cover a named COUNT, the FROM clause, the join, and selecting/grouping by title. The last requirement is a combined point. The scheme also accepts a comma-separated FROM with the join condition in WHERE.'],
 mistakes:['COUNT(*) without GROUP BY produces one total. An unjoined pair of tables multiplies rows and inflates counts. Do not add a filter for MK12: it is an example, not the only show requested.']},
 E063:{title:'Update one game character',commandWord:'Write',
 reading:['Both values must change in the existing row identified by CharacterID. The identifier 0002 is text, including its leading zeros.'],
 solution:[{type:'code',text:'UPDATE CHARACTER\nSET Level = 3, Money = 10000.00\nWHERE CharacterID = "0002";'}, 'SET lists both changes, separated by a comma. WHERE restricts the change to the named character; it does not filter by username or character name.'],
 marking:['The three points are UPDATE of the correct table, SET of both values, and the correct WHERE condition. Changing only one value does not satisfy the combined SET point.'],
 mistakes:['Without WHERE, every character is changed. INSERT would create a row rather than alter the character specified.']}
};
