/* Bounded teaching models: each trace describes only the rules displayed in its panel. */
const Section12Models = (() => {
  'use strict';
  const clone = value => JSON.parse(JSON.stringify(value));
  const shown = value => value === null ? 'Not set' : typeof value === 'boolean' ? String(value).toUpperCase() : typeof value === 'number' ? String(Number(value.toFixed(8))) : String(value);
  const number = (value, name, min, max, integer = true) => {
    if (!['string', 'number'].includes(typeof value) || String(value).trim() === '' || !Number.isFinite(Number(value)) || Number(value) < min || Number(value) > max || (integer && !Number.isInteger(Number(value)))) throw new RangeError(`${name}: enter ${integer ? 'a whole number' : 'a number'} from ${min} to ${max}.`);
    return Number(value);
  };
  const choose = (value, choices, name) => { if (!choices.includes(value)) throw new RangeError(`${name}: choose ${choices.join(' or ')}.`); return value; };
  const n = (name, label, value, min, max, step = 1, when) => ({ name, label, value, type: 'number', min, max, step, when });
  const s = (name, label, value, options, when) => ({ name, label, value, type: 'select', options, when });
  const t = (name, label, value, maxlength = 120) => ({ name, label, value, type: 'text', maxlength });
  const definitions = {
    lifecycle: { title: 'Follow a requirement into working software', note: 'One independent booking requests 1–6 seats. A user then asks for a larger limit. Compare when feedback arrives and which work must be revisited.', fields: [s('model', 'Development approach', 'Iterative', ['Waterfall', 'Iterative', 'RAD']), n('newLimit', 'Requested new upper limit (7–12)', 8, 7, 12)] },
    structure: { title: 'Follow a call, its data and its return', note: 'ReadBooking, CalculateCharge and DisplayCharge are children of BookingController. This example assumes validated input: Seats 1–6, Price 0–100. Repeated receipts do not create more bookings.', fields: [n('seats', 'Seats (1–6)', 3, 1, 6), n('price', 'Price per seat (0–100)', 12.5, 0, 100, 0.5), n('copies', 'Receipt copies (0–3)', 1, 0, 3)] },
    states: { title: 'Change a booking state with events', note: 'Each booking is independent. Available is a fixed per-request limit, not a shared stock counter. submit is allowed only for a whole-number Seats from 1 to Available. pay confirms a Pending booking; cancel returns Pending or Confirmed to Draft. Other events leave the state unchanged.', fields: [n('seats', 'Seats to request (−1–9)', 3, -1, 9), n('available', 'Available for this request (1–8)', 6, 1, 8), t('events', 'Events, separated by commas (1–8)', 'submit, pay, pay, cancel')] },
    debug: { title: 'Locate a fault, repair it, then run again', note: 'Choose one error. Observe the faulty version before revealing the repair. Syntax uses this pseudocode grammar: IF must end with THEN. Runtime division by zero stops the shown run. Logic uses the requirement 1 ≤ Seats ≤ Available.', fields: [s('kind', 'Error type', 'Logic', ['Syntax', 'Logic', 'Runtime']), n('seats', 'Seats (−1–9)', 6, -1, 9, 1, { kind: ['Syntax', 'Logic'] }), n('available', 'Available (1–8)', 6, 1, 8, 1, { kind: ['Syntax', 'Logic'] }), n('total', 'Total seats (0–60)', 0, 0, 60, 1, { kind: ['Runtime'] }), n('groups', 'Number of groups (0–10)', 0, 0, 10, 1, { kind: ['Runtime'] })] },
    testing: { title: 'Test a caller with a stub, then a real module', note: 'The caller prints Accepted or Rejected. The real ValidSeats function accepts integer requests from 1 to 6. Choose a constant TRUE or FALSE stub result to exercise a caller path. Neither constant validates the real rule.', fields: [s('implementation', 'ValidSeats implementation', 'Stub', ['Stub', 'Real module']), s('stubResult', 'Stub return value', 'TRUE', ['TRUE', 'FALSE'], { implementation: ['Stub'] }), s('view', 'Test design view', 'Black-box', ['Black-box', 'White-box']), t('requests', 'Test requests (1–8 integers, −1–9)', '0, 3, 6, 7')] },
    boundary: { title: 'Test both sides of each boundary', note: 'This rule accepts whole numbers in an inclusive interval. Change the limits and predict results before revealing the test log. Decimal and non-numeric validation are outside this model.', fields: [n('lower', 'Lowest accepted integer (0–19)', 1, 0, 19), n('upper', 'Highest accepted integer (1–20)', 6, 1, 20), n('probe', 'One extra integer to test (−1–21)', 3, -1, 21), s('implementation', 'Program condition', 'Faulty upper boundary', ['Faulty upper boundary', 'Correct inclusive rule'])] },
    maintenance: { title: 'Carry a changed requirement through the system', note: 'Version 1 accepts 1–6 seats. A larger event now allows 1–NewLimit. Keep the form, validation code and expected test results consistent. The test harness calls the validator directly; the final integration check also includes the form.', fields: [n('newLimit', 'New limit (7–12)', 8, 7, 12), n('seats', 'Request for the integration check (0–13)', 8, 0, 13), s('patch', 'Changes to apply', 'Form only', ['Form only', 'Form and code', 'Form, code and tests'])] }
  };
  function builder(key, inputs, nodes, code = []) {
    const run = { key, inputs: clone(inputs), nodes, code: typeof code === 'string' ? code.split('\n') : code, frames: [] };
    const state = { title: 'Ready to predict', explanation: 'No step has been revealed.', predict: 'What should happen first?', focus: '', flow: '', variables: {}, artifact: '', output: [], table: null, lines: [], code: run.code, complete: false };
    const add = patch => { Object.assign(state, clone(patch)); run.frames.push(clone(state)); };
    const finish = (patch = {}) => { add({ complete: true, predict: 'Change one input, prepare a new example and explain what you expect to change.', ...patch }); return run; };
    return { run, state, add, finish };
  }
  const list = (value, name, min, max) => {
    const parts = String(value).split(',').map(item => item.trim());
    if (!parts.length || parts.length > 8) throw new RangeError(`${name}: provide 1–8 comma-separated values.`);
    return parts.map(item => number(item, name, min, max));
  };
  const validSeats = (seats, limit = 6, lower = 1) => Number.isInteger(seats) && seats >= lower && seats <= limit;
  function bookingTransition(state, event, seats, available) {
    choose(state, ['Draft', 'Pending', 'Confirmed'], 'State'); choose(event, ['submit', 'pay', 'cancel'], 'Event');
    if (state === 'Draft' && event === 'submit') return { state: validSeats(seats, available) ? 'Pending' : 'Draft', reason: validSeats(seats, available) ? 'The guard is TRUE: the request can wait for payment.' : 'The guard is FALSE: reject the request and stay in Draft.', guard: validSeats(seats, available) };
    if (state === 'Pending' && event === 'pay') return { state: 'Confirmed', reason: 'Payment confirms this pending booking.', guard: null };
    if (state !== 'Draft' && event === 'cancel') return { state: 'Draft', reason: 'Cancellation returns this booking to Draft.', guard: null };
    return { state, reason: `There is no state-changing ${event} transition from ${state}. This model ignores the event.`, guard: null };
  }
  function prepare(key, raw = {}) {
    if (!Object.prototype.hasOwnProperty.call(definitions, key)) throw new RangeError('Unknown Section 12 activity.');
    const supplied = Object.fromEntries(definitions[key].fields.map(field => [field.name, raw[field.name] ?? field.value]));
    const i = {}, read = (name, min, max, integer = true) => i[name] = number(supplied[name], name, min, max, integer);
    const select = name => i[name] = choose(supplied[name], definitions[key].fields.find(field => field.name === name).options, name);
    if (key === 'lifecycle') {
      const model = select('model'), newLimit = read('newLimit', 7, 12);
      const q = builder(key, i, ['Analysis', 'Design', 'Development', 'Testing', 'Maintenance']);
      q.add({ title: 'A user needs a booking form', explanation: 'The existing requirement accepts independent whole-number requests from 1 to 6 seats. First decide what evidence the developer needs.', predict: 'What must analysis make precise?', variables: { Approach: model, AgreedLimit: 6, ImplementedLimit: 'Not built' }, artifact: 'User brief: “Let me request seats and tell me whether the request is valid.”' });
      q.add({ title: 'Analysis produces a testable requirement', focus: 'Analysis', flow: 'User brief → requirements', artifact: 'Requirement R1: accept integer Seats from 1 to 6 inclusive; otherwise display Rejected. Each request is independent.', explanation: '“Valid” now has an exact meaning. The examples 0, 1, 6 and 7 can check the requirement.', predict: 'Which design would meet R1?' });
      q.add({ title: 'Design divides the work', focus: 'Design', flow: 'Requirements → module interfaces', artifact: 'BookingController → ReadBooking → ValidSeats(Seats, Limit) → DisplayDecision. ValidSeats returns BOOLEAN; the caller chooses the message.', explanation: 'This list is execution order. The controller calls the modules; the child modules do not call one another.', predict: model === 'RAD' ? 'Can a clickable prototype already prove that validation works?' : 'What must the validation function return for 6?' });
      if (model === 'RAD') {
        q.add({ title: 'Build a prototype for user feedback', focus: 'Development', flow: 'Interface design → clickable prototype', variables: { Approach: model, AgreedLimit: 6, ImplementedLimit: 'Prototype only' }, artifact: 'Prototype form: [Seats] [Submit]. Clicking Submit displays a sample message; it does not yet run real validation.', explanation: 'This prototype helps the user judge the screen and workflow. Its sample response is not evidence that the rule works.', predict: 'The user requests a limit of ' + newLimit + '. Which artifact must change first?' });
        q.add({ title: 'Review the prototype with the user', focus: 'Analysis', flow: 'User feedback → revised requirement', variables: { Approach: model, AgreedLimit: newLimit, ImplementedLimit: 'Prototype only' }, artifact: `Feedback: allow ${newLimit} seats. Revised R1: accept 1–${newLimit} inclusive. Update the form label and the validation design.`, explanation: 'In this RAD example, users review prototypes frequently. The revised requirement still needs working code and tests.', predict: 'Which boundary tests should the final product pass?' });
      }
      const firstLimit = model === 'RAD' ? newLimit : 6;
      q.add({ title: 'Development implements the agreed rule', focus: 'Development', flow: 'Module design → working validator', variables: { Approach: model, AgreedLimit: firstLimit, ImplementedLimit: firstLimit }, artifact: `ValidSeats returns (Seats >= 1) AND (Seats <= ${firstLimit}).`, explanation: 'A Boolean return value lets the caller select Accepted or Rejected. This is working validation, rather than a sample prototype response.', predict: `Predict the outputs for 0, 1, ${firstLimit} and ${firstLimit + 1}.` });
      q.add({ title: 'Testing compares expected and actual results', focus: 'Testing', flow: 'Requirement + program → test evidence', table: { headers: ['Seats', 'Expected', 'Actual'], rows: [0, 1, firstLimit, firstLimit + 1].map(v => [v, validSeats(v, firstLimit) ? 'Accepted' : 'Rejected', validSeats(v, firstLimit) ? 'Accepted' : 'Rejected']) }, artifact: 'Boundary tests pass for the currently agreed requirement.', explanation: 'Passing tests supports this requirement for these cases. It does not prove the program contains no faults.', predict: model === 'RAD' ? 'What evidence supports release beyond the prototype?' : `What happens when the user now requests ${newLimit} seats?` });
      if (model !== 'RAD') {
        q.add({ title: model === 'Waterfall' ? 'A released version receives a change request' : 'Review an increment and choose the next improvement', focus: model === 'Waterfall' ? 'Maintenance' : 'Analysis', flow: model === 'Waterfall' ? 'Released version → change request → analysis' : 'Working increment → user feedback → next iteration', table: null, artifact: `New request: increase the allowed maximum from 6 to ${newLimit}. Existing code still rejects ${newLimit}.`, explanation: model === 'Waterfall' ? 'This example follows planned phases before release. The later change still needs analysis, design, implementation and testing; waterfall does not make later change impossible.' : 'This example delivers a small working increment, gathers feedback and then repeats the relevant activities for the next increment.', predict: 'Can changing only the form label implement the request?' });
        q.add({ title: 'Revisit the affected artifacts', focus: 'Design', flow: 'Revised requirement → updated design and test expectations', variables: { Approach: model, AgreedLimit: newLimit, ImplementedLimit: 6 }, artifact: `Requirement and form: 1–${newLimit}. Validation design: upper limit ${newLimit}. New boundary tests: ${newLimit} must be accepted; ${newLimit + 1} must be rejected.`, explanation: 'The requirement, interface and test expectations change together. The running validator has not been updated yet.', predict: `What will the old code actually do with ${newLimit}?` });
        q.add({ title: 'Implement the change', focus: 'Development', flow: 'Revised design → revised validator', variables: { Approach: model, AgreedLimit: newLimit, ImplementedLimit: newLimit }, artifact: `ValidSeats now returns (Seats >= 1) AND (Seats <= ${newLimit}).`, explanation: 'The code now reflects the new upper limit. Run new tests and retain tests for unchanged behaviour.', predict: 'Should 0 still be rejected after this change?' });
        q.add({ title: 'Retest the changed and unchanged behaviour', focus: 'Testing', flow: 'Revised requirement + revised code → new test evidence', table: { headers: ['Seats', 'Expected', 'Actual'], rows: [0, 1, 6, newLimit, newLimit + 1].map(v => [v, validSeats(v, newLimit) ? 'Accepted' : 'Rejected', validSeats(v, newLimit) ? 'Accepted' : 'Rejected']) }, artifact: '0 remains invalid; 1 and 6 remain valid; the new upper boundary is included.', explanation: 'The new requirement intentionally changes the result for requests above 6. Unchanged behaviour must still work.', predict: 'Which artifacts would need attention if the rule changes again?' });
      }
      return q.finish({ title: 'Explain the development approach', explanation: model === 'Waterfall' ? 'This path used planned phases for the first release and a controlled change cycle afterwards.' : model === 'Iterative' ? 'This path used a working increment, feedback and another iteration.' : 'This path used a prototype for rapid user feedback, followed by real implementation and testing.', artifact: 'All three need clear requirements, a suitable design, working code and evidence from testing. Timing and organisation differ.' });
    }
    if (key === 'structure') {
      const seats = read('seats', 1, 6), price = read('price', 0, 100, false), copies = read('copies', 0, 3);
      const code = `PROCEDURE ReadBooking(BYREF Seats : INTEGER, BYREF Price : REAL)\n    INPUT Seats\n    INPUT Price\nENDPROCEDURE\nFUNCTION CalculateCharge(BYVAL Quantity : INTEGER, BYVAL PriceEach : REAL) RETURNS REAL\n    RETURN Quantity * PriceEach\nENDFUNCTION\nPROCEDURE DisplayCharge(BYVAL Amount : REAL)\n    OUTPUT Amount\nENDPROCEDURE\nPROCEDURE BookingController\n    DECLARE Seats, Copy : INTEGER\n    DECLARE Price, Total : REAL\n    CALL ReadBooking(Seats, Price)\n    Total ← CalculateCharge(Seats, Price)\n    FOR Copy ← 1 TO ${copies}\n        CALL DisplayCharge(Total)\n    NEXT Copy\nENDPROCEDURE\nCALL BookingController`;
      const q = builder(key, i, ['BookingController', 'ReadBooking', 'CalculateCharge', 'DisplayCharge'], code);
      const variables = { Seats: null, Price: null, Total: null, Copy: null };
      q.add({ title: 'The controller is ready to start', focus: 'BookingController', variables, explanation: 'Execution will begin with CALL BookingController after the subprogram definitions. No module body has run yet. Seats and Price have not received input.', predict: 'Where does the final CALL transfer control?', artifact: `Prepared input: Seats = ${seats}; Price = ${price}. Receipt copies = ${copies}.` });
      q.add({ title: 'The controller begins', lines: [20, 11, 12, 13], explanation: 'The main call enters BookingController. Its declarations establish local storage without assigning starting values.', predict: 'Which child module receives control first?' });
      q.add({ title: 'Call ReadBooking', focus: 'ReadBooking', lines: [14, 1], flow: 'BookingController → ReadBooking; reference parameters bind to caller Seats and Price', variables: { ...variables, 'ReadBooking.Seats (BYREF)': 'alias of caller Seats', 'ReadBooking.Price (BYREF)': 'alias of caller Price' }, explanation: 'ReadBooking has reference parameters with the same names as the caller’s variables. Each refers to the corresponding caller variable; a matching name alone would not create this link without BYREF.', predict: 'Which caller variable changes when INPUT Seats runs?' });
      variables.Seats = seats;
      q.add({ title: 'Input through a reference', lines: [2], variables: { ...variables, 'ReadBooking.Seats (BYREF)': seats, 'ReadBooking.Price (BYREF)': 'alias of caller Price' }, explanation: `INPUT Seats inside ReadBooking stores ${seats} in the controller’s Seats variable through the reference parameter.`, predict: 'Which caller variable receives the next input?' });
      variables.Price = price;
      q.add({ title: 'Read the price', lines: [3], variables: { ...variables, 'ReadBooking.Seats (BYREF)': seats, 'ReadBooking.Price (BYREF)': price }, explanation: `INPUT Price stores ${price} in the controller’s Price. The values remain when ReadBooking ends.`, predict: 'Where does control return?' });
      q.add({ title: 'Return to the controller', focus: 'BookingController', lines: [4], flow: 'ReadBooking → BookingController; control returns after CALL', variables, explanation: 'ENDPROCEDURE returns control. It does not return a function value; the two caller variables were updated through references.', predict: 'What values will CalculateCharge receive?' });
      q.add({ title: 'Call the function with copies', focus: 'CalculateCharge', lines: [15, 5], flow: `BookingController → CalculateCharge; Quantity = ${seats}, PriceEach = ${price}`, variables: { ...variables, 'local.Quantity': seats, 'local.PriceEach': price }, explanation: 'BYVAL gives the function local copies. Parameter position pairs Seats with Quantity and Price with PriceEach.', predict: 'What will the function return? Is Total assigned yet?' });
      const total = seats * price;
      q.add({ title: 'Return a value', lines: [6], flow: `CalculateCharge → calling expression; return ${shown(total)}`, variables: { ...variables, 'local.Quantity': seats, 'local.PriceEach': price, 'Returned value': total }, explanation: `RETURN evaluates ${seats} × ${price}. It sends the value ${shown(total)} to the calling expression. It does not display a receipt.`, predict: 'Which statement stores the returned value?' });
      variables.Total = total;
      q.add({ title: 'Store the function result', focus: 'BookingController', lines: [15], flow: `CalculateCharge → BookingController; Total ← ${shown(total)}`, variables, explanation: 'The assignment stores the returned value in Total. Function-local names no longer exist.', predict: copies ? 'How many times will the receipt module be called?' : 'Will a FOR loop from 1 to 0 call the receipt module?' });
      for (let copy = 1; copy <= copies; copy++) {
        variables.Copy = copy;
        q.add({ title: `Receipt ${copy} of ${copies}`, focus: 'DisplayCharge', lines: [16, 17, 8], flow: `BookingController → DisplayCharge; Amount = ${shown(total)}`, variables: { ...variables, 'local.Amount': total }, explanation: 'The controller repeats this child-module call. It passes the same Total value each time; it does not calculate or book the seats again.', predict: 'What is displayed, and which variable remains unchanged?' });
        q.add({ title: 'Display this copy', lines: [9], output: [...q.state.output, shown(total)], explanation: `OUTPUT writes ${shown(total)}. DisplayCharge is a procedure, so it does not supply a returned value to an expression.`, predict: 'Does control return to the controller or to CalculateCharge?' });
        q.add({ title: 'Return after the receipt call', focus: 'BookingController', lines: [10, 18], flow: 'DisplayCharge → BookingController; continue the loop', variables, explanation: 'Control returns to the statement after CALL, then NEXT advances the counter.', predict: copy < copies ? 'Which child module is called again?' : 'Has the final receipt been produced?' });
      }
      variables.Copy = copies + 1;
      return q.finish({ title: 'The controller finishes', focus: 'BookingController', lines: [19], variables, flow: 'BookingController → main call; all calls completed', artifact: 'Final recorded controller values. Its local variables end when it returns.', explanation: `${copies} receipt(s) were displayed. Seats was ${seats}, Price was ${price}, and Total was ${shown(total)}. ${copies === 0 ? 'The FOR loop made zero calls to DisplayCharge.' : 'The repeated calls changed neither Seats nor Total.'}` });
    }
    if (key === 'states') {
      const seats = read('seats', -1, 9), available = read('available', 1, 8);
      const events = String(supplied.events).split(',').map(value => value.trim().toLowerCase());
      if (!events.length || events.length > 8) throw new RangeError('Events: provide 1–8 events, separated by commas.');
      events.forEach(event => choose(event, ['submit', 'pay', 'cancel'], 'Event')); i.events = events.join(', ');
      const q = builder(key, i, ['Draft', 'Pending', 'Confirmed']); let state = 'Draft';
      q.add({ title: 'Start in Draft', focus: state, variables: { State: state, Seats: seats, Available: available }, artifact: 'State describes the booking now. An event is something that happens; a guard is a condition that must be true.', explanation: 'No event has occurred. “Pending” means a valid request is waiting for payment.', predict: `The first event is ${events[0]}. Will the state change?` });
      const rows = [];
      for (let index = 0; index < events.length; index++) {
        const event = events[index], before = state, transition = bookingTransition(state, event, seats, available); state = transition.state;
        rows.push([before, event, transition.guard === null ? 'No guard on this transition' : shown(transition.guard), state]);
        q.add({ title: `Event ${index + 1}: ${event}`, focus: state, flow: `${before} → ${state} on ${event}${before === state ? ' (self-loop)' : ''}`, variables: { State: state, Seats: seats, Available: available, 'Guard on submit from Draft': validSeats(seats, available) }, table: { headers: ['Before', 'Event', 'Guard', 'After'], rows }, explanation: transition.reason + (before === state ? ' The event occurred even though the state did not change.' : ''), predict: index + 1 < events.length ? `Next event: ${events[index + 1]}. Predict the next state from ${state}.` : 'Which events changed the state, and which produced a self-loop?' });
      }
      return q.finish({ title: 'Read the event history', explanation: `The final state is ${state}. Available stayed at ${available}: this model follows one independent request and does not manage a shared seat inventory.` });
    }
    if (key === 'debug') {
      const kind = select('kind');
      const seats = kind === 'Runtime' ? null : read('seats', -1, 9), available = kind === 'Runtime' ? null : read('available', 1, 8);
      const total = kind === 'Runtime' ? read('total', 0, 60) : null, groups = kind === 'Runtime' ? read('groups', 0, 10) : null;
      const selection = (operator, then = true) => `DECLARE Seats, Available : INTEGER\nINPUT Seats\nINPUT Available\nIF (Seats >= 1) AND (Seats ${operator} Available)${then ? ' THEN' : ''}\n    OUTPUT "Accepted"\nELSE\n    OUTPUT "Rejected"\nENDIF`;
      const faulty = kind === 'Runtime' ? 'DECLARE Total, Groups : INTEGER\nINPUT Total\nINPUT Groups\nOUTPUT Total / Groups' : selection(kind === 'Logic' ? '<' : '<=', kind !== 'Syntax');
      const fixed = kind === 'Runtime' ? 'DECLARE Total, Groups : INTEGER\nINPUT Total\nINPUT Groups\nIF Groups > 0 THEN\n    OUTPUT Total / Groups\nELSE\n    OUTPUT "No data"\nENDIF' : selection('<=');
      const expected = kind === 'Runtime' ? groups === 0 ? 'No data' : shown(total / groups) : validSeats(seats, available) ? 'Accepted' : 'Rejected';
      const variables = kind === 'Runtime' ? { Total: total, Groups: groups } : { Seats: seats, Available: available };
      const q = builder(key, i, ['Predict', 'Observe fault', 'Locate', 'Repair', 'Retest'], faulty);
      q.add({ title: 'Read the requirement before the result', focus: 'Predict', variables: { ...variables, Expected: expected, Version: 'Faulty' }, artifact: kind === 'Runtime' ? 'Report Total / Groups when Groups > 0; otherwise report No data. Inputs are non-negative integers. Total must be 0 when Groups is 0 in a real consistent dataset; this model also permits inconsistent input to check the guard.' : `Accept a whole-number request only when 1 ≤ Seats ≤ ${available}.`, explanation: 'The expected result comes from the requirement, not from the program under test. Read the code and predict the actual behaviour.', predict: `Will the faulty program produce ${expected}, stop with an error, or fail the syntax check?` });
      const actual = kind === 'Syntax' ? 'Syntax error: THEN missing; no statements execute' : kind === 'Runtime' ? groups === 0 ? 'Runtime error: division by zero; execution stops' : shown(total / groups) : seats >= 1 && seats < available ? 'Accepted' : 'Rejected';
      q.add({ title: 'Observe the faulty version', focus: 'Observe fault', lines: kind === 'Runtime' ? [4] : [4], variables: { ...variables, Expected: expected, Actual: actual, Version: 'Faulty' }, output: kind === 'Syntax' || (kind === 'Runtime' && groups === 0) ? [] : [actual], explanation: kind === 'Syntax' ? 'The missing THEN breaks the stated pseudocode grammar. The program cannot begin executing.' : kind === 'Runtime' && groups === 0 ? 'The statements are syntactically valid. Execution reaches division by zero and stops before OUTPUT can produce a value.' : actual === expected ? 'This input produces the expected output. One passing case does not show that the program is fault-free.' : 'The program runs to the end, but the actual result disagrees with the requirement.', predict: 'Which statement is responsible, and what minimal change addresses it?' });
      q.add({ title: 'Locate the cause', focus: 'Locate', artifact: kind === 'Syntax' ? 'Fault: line 4 needs THEN at the end of the IF header.' : kind === 'Logic' ? 'Fault: Seats < Available excludes the upper boundary. The requirement includes it.' : 'Fault: division is attempted without checking Groups. A zero divisor has no valid quotient.', explanation: kind === 'Logic' ? `At Seats = Available = ${available}, the faulty comparison is FALSE. Test the exact upper boundary to expose this fault.` : kind === 'Runtime' ? 'Set Groups to 0 to exercise the failure path. A non-zero Groups value may conceal the missing guard.' : 'A syntax checker can identify a grammar problem, but the programmer must make a valid correction.', predict: 'After the correction, what should this same input produce?' });
      q.add({ title: 'Reveal the repair', focus: 'Repair', code: fixed.split('\n'), lines: [4], variables: { ...variables, Expected: expected, Version: 'Fixed; not yet rerun' }, output: [], explanation: kind === 'Syntax' ? 'Add THEN. Do not change the required acceptance condition.' : kind === 'Logic' ? 'Replace < with <=. Preserve the lower-bound check.' : 'Check Groups > 0 before dividing; otherwise output No data.', artifact: 'The prepared pseudocode has changed. Open it to inspect the repair. The repaired version has not yet been rerun.', predict: 'Will the rerun now match the expected result?' });
      q.add({ title: 'Rerun the same input', focus: 'Retest', lines: kind === 'Runtime' ? [groups > 0 ? 5 : 7] : [validSeats(seats, available) ? 5 : 7], variables: { ...variables, Expected: expected, Actual: expected, Version: 'Fixed', Match: true }, output: [expected], artifact: 'Expected and actual now agree for this input.', explanation: 'Repeating the same input checks the correction. Other relevant inputs are still needed to test the program more widely.', predict: kind === 'Runtime' ? 'Which second test checks the other branch?' : 'Which tests check just below and just above each accepted boundary?' });
      return q.finish({ title: 'Choose another revealing input', lines: [], explanation: 'Syntax faults prevent this program from starting; runtime faults occur during an attempted execution; logic faults can finish with a wrong result. Inputs determine which runtime and logic faults become visible.' });
    }
    if (key === 'testing') {
      const implementation = select('implementation'), stubResult = select('stubResult') === 'TRUE', view = select('view'), requests = list(supplied.requests, 'Test requests', -1, 9); i.requests = requests.join(', ');
      const source = `FUNCTION ValidSeats(BYVAL Seats : INTEGER) RETURNS BOOLEAN\n    RETURN ${implementation === 'Stub' ? shown(stubResult) : '(Seats >= 1) AND (Seats <= 6)'}\nENDFUNCTION\nDECLARE Seats : INTEGER\nINPUT Seats\nIF ValidSeats(Seats) THEN\n    OUTPUT "Accepted"\nELSE\n    OUTPUT "Rejected"\nENDIF`;
      const q = builder(key, i, ['Requirement', 'Prepare', 'Execute', 'Compare'], view === 'White-box' ? source : []);
      const rows = [], seen = new Set(); let failures = 0;
      q.add({ title: 'Choose test cases before running', focus: 'Requirement', variables: { Implementation: implementation, 'Stub return': implementation === 'Stub' ? stubResult : 'Not used', View: view, TestsRun: 0, Failures: 0 }, artifact: view === 'Black-box' ? 'Interface: ValidSeats(INTEGER) RETURNS BOOLEAN. Required rule: accept 1–6 inclusive. Choose cases from this specification without reading the implementation.' : 'Inspect the caller’s IF. Choose cases to exercise its TRUE and FALSE outcomes. Statement and branch coverage refer to executed code, not proof of correctness.', explanation: implementation === 'Stub' ? `The selected substitute returns ${shown(stubResult)} for every test. It isolates the caller while the real function is unavailable.` : 'The selected function implements the stated rule. Each request runs independently.', predict: `The first input is ${requests[0]}. What does the requirement say?` });
      requests.forEach((seats, index) => {
        const expected = validSeats(seats) ? 'Accepted' : 'Rejected', accepted = implementation === 'Stub' ? stubResult : validSeats(seats), actual = accepted ? 'Accepted' : 'Rejected';
        q.add({ title: `Prepare test ${index + 1}`, focus: 'Prepare', lines: [], variables: { Implementation: implementation, View: view, Seats: seats, Expected: expected, TestsRun: index, Failures: failures }, table: { headers: ['Input', 'Expected', 'Actual', 'Result'], rows: [...rows, [seats, expected, 'Not run', 'Not checked']] }, explanation: 'Record the expected result from the requirement before executing the program.', predict: `Will the selected ${implementation.toLowerCase()} return TRUE or FALSE for ${seats}?` });
        seen.add(accepted); failures += actual === expected ? 0 : 1;
        rows.push([seats, expected, actual, actual === expected ? 'PASS' : 'FAIL']);
        q.add({ title: `Run and compare test ${index + 1}`, focus: 'Compare', lines: view === 'White-box' ? [2, 6, accepted ? 7 : 9] : [], variables: { Implementation: implementation, View: view, Seats: seats, Returned: accepted, Expected: expected, Actual: actual, TestsRun: index + 1, Failures: failures, 'Caller IF outcomes visited': `${seen.size} of 2` }, table: { headers: ['Input', 'Expected', 'Actual', 'Result'], rows }, output: [...q.state.output, `Test ${index + 1}: ${actual}`], explanation: actual === expected ? 'The observed output matches this test’s expected output.' : 'The observed output fails the real booking rule. A stub is a planned substitute, so this identifies a limitation of the substitute rather than a discovered fault in the unavailable real module.', predict: index + 1 < requests.length ? `Next input: ${requests[index + 1]}. Which outcome should it exercise?` : 'Did these tests exercise both caller branches? What can the evidence establish?' });
      });
      return q.finish({ title: 'Interpret the evidence', focus: 'Compare', lines: [], explanation: `${requests.length} tests ran; ${failures} failed against the real requirement. ${seen.size} of the caller’s 2 IF outcomes were visited. ${implementation === 'Stub' ? 'A constant stub checks only one caller path. Change its return value to check the other path; then replace the stub with the real module and rerun the tests.' : 'Passing these cases and visiting both branches still cannot prove that every possible fault is absent.'}`, artifact: view === 'Black-box' ? 'Black-box cases were selected from the input/output rule. The results can be checked without inspecting the implementation.' : 'White-box evidence: the caller’s TRUE/FALSE outcomes. This activity does not claim full path or condition coverage.' });
    }
    if (key === 'boundary') {
      const lower = read('lower', 0, 19), upper = read('upper', 1, 20), probe = read('probe', -1, 21), implementation = select('implementation');
      if (lower >= upper) throw new RangeError('The lower bound must be smaller than the upper bound.');
      const faulty = implementation === 'Faulty upper boundary';
      const q = builder(key, i, ['Rule', 'Select data', 'Execute', 'Compare'], `FUNCTION ValidSeats(BYVAL Seats : INTEGER) RETURNS BOOLEAN\n    RETURN (Seats >= ${lower}) AND (Seats ${faulty ? '<' : '<='} ${upper})\nENDFUNCTION`);
      const values = [...new Set([lower - 1, lower, lower + 1, upper - 1, upper, upper + 1, probe])], rows = []; let failures = 0;
      q.add({ title: 'Separate the rule from the implementation', focus: 'Rule', variables: { Lower: lower, Upper: upper }, artifact: `Specification: accept integer Seats from ${lower} to ${upper}, inclusive. Program condition: Seats >= ${lower} AND Seats ${faulty ? '<' : '<='} ${upper}.`, explanation: 'The specification decides the expected result. The actual result comes from the selected implementation.', predict: 'Which value is most likely to expose a disagreement?' });
      values.forEach((value, index) => {
        const expected = validSeats(value, upper, lower), actual = value >= lower && (faulty ? value < upper : value <= upper);
        const role = value < lower || value > upper ? 'Outside: invalid' : value === lower || value === upper ? 'Boundary: valid' : 'Inside: valid';
        q.add({ title: `Predict Seats = ${value}`, focus: 'Select data', lines: [], table: { headers: ['Seats', 'Data role', 'Expected', 'Actual', 'Result'], rows: [...rows, [value, role, expected ? 'TRUE' : 'FALSE', 'Not run', 'Not checked']] }, variables: { Lower: lower, Upper: upper, Seats: value }, explanation: `${value} is ${role.toLowerCase()}. Classify it using the requirement, then predict the program’s result.`, predict: `Will the shown condition return ${shown(expected)}?` });
        failures += expected === actual ? 0 : 1; rows.push([value, role, shown(expected), shown(actual), expected === actual ? 'PASS' : 'FAIL']);
        q.add({ title: `Reveal Seats = ${value}`, focus: 'Compare', lines: [2], variables: { Lower: lower, Upper: upper, Seats: value, Expected: expected, Actual: actual, Failures: failures }, table: { headers: ['Seats', 'Data role', 'Expected', 'Actual', 'Result'], rows }, explanation: expected === actual ? 'The implementation agrees with the requirement for this input.' : `The strict comparison excludes ${upper}, even though the requirement includes it.`, predict: index + 1 < values.length ? `Next input: ${values[index + 1]}. Predict its result.` : 'Which single change would fix the boundary fault?' });
      });
      return q.finish({ title: 'Use the test log to justify a conclusion', lines: [], explanation: `${values.length} distinct values were tested; ${failures} failed. Adjacent limits can make boundary-neighbour values overlap, so duplicates are tested once. ${faulty ? `Replacing < ${upper} with <= ${upper} fixes the excluded upper endpoint in this model.` : 'Every tested value matched the inclusive rule.'}` });
    }
    if (key === 'maintenance') {
      const newLimit = read('newLimit', 7, 12), seats = read('seats', 0, 13), patch = select('patch');
      const codeChanged = patch !== 'Form only', testsChanged = patch === 'Form, code and tests';
      const code = limit => [`FUNCTION ValidSeats(BYVAL Seats : INTEGER) RETURNS BOOLEAN`, `    RETURN (Seats >= 1) AND (Seats <= ${limit})`, 'ENDFUNCTION'];
      const q = builder(key, i, ['Requirement', 'Form', 'Code', 'Tests', 'Integration'], code(6));
      const variables = { RequiredLimit: 6, FormLimit: 6, CodeLimit: 6, TestExpectedLimit: 6 };
      q.add({ title: 'Version 1 is consistent', focus: 'Requirement', variables, artifact: 'Requirement, form, code and tests all use the inclusive range 1–6.', explanation: 'The user now asks to support a larger event. This is a changed requirement, not evidence that version 1 broke its original rule.', predict: `If the new maximum is ${newLimit}, which artifacts must be reviewed?` });
      variables.RequiredLimit = newLimit;
      q.add({ title: 'Agree the new requirement', focus: 'Requirement', variables, artifact: `Version 2 must accept independent requests from 1 to ${newLimit}. Keep 0 invalid.`, explanation: 'The new requirement intentionally changes the expected outcome for some values that were previously invalid.', predict: 'Does changing the visible form also change the validator?' });
      variables.FormLimit = newLimit;
      q.add({ title: 'Update the form', focus: 'Form', variables, artifact: `Form label: Seats (1–${newLimit}). Form upper-limit check: ${newLimit}. Selected change set: ${patch}.`, explanation: `The form can now pass ${newLimit}, but the unchanged validator still rejects it. An interface edit does not automatically modify a separate module.`, predict: 'What will the selected change set do to the code?' });
      if (codeChanged) variables.CodeLimit = newLimit;
      q.add({ title: codeChanged ? 'Update the validation code' : 'Leave the validation code unchanged', focus: 'Code', code: code(variables.CodeLimit), lines: [2], variables, artifact: `Code upper limit = ${variables.CodeLimit}; required upper limit = ${newLimit}.`, explanation: codeChanged ? 'The real validator now implements the new requirement.' : 'This incomplete change set leaves a mismatch between the form and the validator.', predict: 'Should a test for 7 still expect rejection under the new requirement?' });
      if (testsChanged) variables.TestExpectedLimit = newLimit;
      q.add({ title: testsChanged ? 'Update affected test expectations' : 'Keep the old test expectations', focus: 'Tests', lines: [], variables, artifact: testsChanged ? `Expected results now use 1–${newLimit}. Add the new upper boundary and its neighbour; retain 0, 1 and 6.` : 'Expected results still use 1–6. The test record has not caught up with the agreed requirement.', explanation: testsChanged ? 'The expected results come from the new requirement. Tests for unchanged behaviour remain useful.' : 'An old expected result can be wrong after an intentional requirement change. A green test log against a stale requirement is not enough.', predict: 'Will the actual results agree with these saved expected results?' });
      const rows = [], values = [...new Set([0, 1, 6, 7, newLimit, newLimit + 1])]; let failures = 0;
      for (const value of values) {
        const savedExpected = validSeats(value, variables.TestExpectedLimit), required = validSeats(value, newLimit), actual = validSeats(value, variables.CodeLimit);
        failures += savedExpected === actual ? 0 : 1;
        rows.push([value, shown(savedExpected), shown(actual), savedExpected === actual ? 'PASS' : 'FAIL', savedExpected === required ? 'Current' : 'STALE']);
        q.add({ title: `Run validator test: ${value}`, focus: 'Tests', lines: [2], variables: { ...variables, TestsRun: rows.length, Failures: failures }, table: { headers: ['Seats', 'Saved expected', 'Actual', 'Test result', 'Expectation'], rows }, explanation: savedExpected !== required ? `The saved expectation for ${value} contradicts the new requirement. Update it from the requirement, not simply to match the code.` : savedExpected === actual ? 'The current expected result matches the validator output.' : 'The expected result follows the new requirement, but the validator output does not.', predict: 'Do the test outcomes alone establish that all artifacts are consistent?' });
      }
      const formAllows = validSeats(seats, variables.FormLimit), validatorAllows = validSeats(seats, variables.CodeLimit), accepted = formAllows && validatorAllows, required = validSeats(seats, newLimit);
      return q.finish({ title: 'Check the integrated booking path', focus: 'Integration', lines: [], variables: { ...variables, TestsRun: rows.length, Failures: failures, Request: seats, 'Form permits': formAllows, 'Validator permits': formAllows ? validatorAllows : 'Not called', 'System accepts': accepted, 'New requirement expects': required, 'All artifacts aligned': codeChanged && testsChanged }, flow: `Seats ${seats} → form ${shown(formAllows)} → validator ${formAllows ? shown(validatorAllows) : 'not called'} → ${accepted ? 'Accepted' : 'Rejected'}`, explanation: `The request is ${accepted ? 'accepted' : 'rejected'}. ${accepted === required ? 'This case matches the new requirement.' : 'This case fails the new requirement.'} ${codeChanged && testsChanged ? 'Form, code and test expectations are aligned.' : 'The change remains incomplete: inspect the artifact limits, even if this particular request or saved test log passes.'}`, artifact: 'After changing a requirement: update affected artifacts, rerun relevant tests, and check the integrated user path.' });
    }
    throw new RangeError('The requested activity is not implemented.');
  }
  return { definitions, prepare, shown, validSeats, bookingTransition };
})();
if (typeof module !== 'undefined' && module.exports) module.exports = Section12Models;
if (typeof window !== 'undefined') window.Section12Models = Section12Models;
