/* Generated by scripts/generate-course-catalog.mjs. Do not edit by hand. */
(function () {
  "use strict";
  const lessons = [
  {
    "number": 1,
    "id": "001",
    "title": "Bits, bytes, nibbles and storage units",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 2,
    "id": "002",
    "title": "Binary place value and denary conversion",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 3,
    "id": "003",
    "title": "Hexadecimal notation and binary grouping",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 4,
    "id": "004",
    "title": "Binary addition, carries and overflow",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 5,
    "id": "005",
    "title": "Signed binary: sign-and-magnitude, one’s complement and two’s complement",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 6,
    "id": "006",
    "title": "Binary fractions and precision limits",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 7,
    "id": "007",
    "title": "Character sets: ASCII, extended ASCII and Unicode",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 8,
    "id": "008",
    "title": "Bitmap images: pixels, resolution and colour depth",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 9,
    "id": "009",
    "title": "Image file size calculations and metadata",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 10,
    "id": "010",
    "title": "Digital sound: sampling rate, sample resolution and duration",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 11,
    "id": "011",
    "title": "Sound file size calculations",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 12,
    "id": "012",
    "title": "Compression: lossless vs lossy",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 13,
    "id": "013",
    "title": "Run-length encoding and dictionary-style compression",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 14,
    "id": "014",
    "title": "Choosing data representation for a real system",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 15,
    "id": "015",
    "title": "Section 1 review under exam timing",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 16,
    "id": "016",
    "title": "Network purposes, LAN, WAN and topologies",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 17,
    "id": "017",
    "title": "Client-server and peer-to-peer models",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 18,
    "id": "018",
    "title": "Packet switching, routing and packet structure",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 19,
    "id": "019",
    "title": "Protocols and layered communication",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 20,
    "id": "020",
    "title": "IP addresses, MAC addresses, DNS and URLs",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 21,
    "id": "021",
    "title": "HTTP, HTTPS, FTP, SMTP, POP3 and IMAP in context",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 22,
    "id": "022",
    "title": "Wired and wireless transmission media",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 23,
    "id": "023",
    "title": "Network hardware: switches, routers, access points and gateways",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 24,
    "id": "024",
    "title": "Internet, intranet, extranet and cloud services",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 25,
    "id": "025",
    "title": "Network performance, latency, bandwidth and congestion",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 26,
    "id": "026",
    "title": "Section 2 review: explaining communication with precision",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 27,
    "id": "027",
    "title": "Computer system overview: input, output, storage, processor and memory",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 28,
    "id": "028",
    "title": "Input devices and data capture",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 29,
    "id": "029",
    "title": "Output devices and user feedback",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 30,
    "id": "030",
    "title": "Primary storage: RAM, ROM, cache and virtual memory",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 31,
    "id": "031",
    "title": "Secondary storage: magnetic, optical and solid-state media",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 32,
    "id": "032",
    "title": "Storage characteristics: capacity, speed, durability, portability and cost",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 33,
    "id": "033",
    "title": "Embedded systems and microcontrollers",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 34,
    "id": "034",
    "title": "Sensors, actuators and control systems",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 35,
    "id": "035",
    "title": "Logic gates: NOT, AND, OR, NAND, NOR, XOR",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 36,
    "id": "036",
    "title": "Truth tables and Boolean expressions",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 37,
    "id": "037",
    "title": "Building logic circuits from requirements",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 38,
    "id": "038",
    "title": "Hardware selection for different users",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 39,
    "id": "039",
    "title": "Environmental and reliability considerations in hardware",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 40,
    "id": "040",
    "title": "Section 3 review: compare, justify, calculate",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 41,
    "id": "041",
    "title": "CPU architecture: ALU, CU, registers, buses and clock",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 42,
    "id": "042",
    "title": "The fetch-decode-execute cycle",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 43,
    "id": "043",
    "title": "Registers: PC, CIR, MAR, MDR, ACC and status register",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 44,
    "id": "044",
    "title": "System buses: address, data and control",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 45,
    "id": "045",
    "title": "Instruction sets and machine code",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 46,
    "id": "046",
    "title": "Assembly language basics and mnemonics",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 47,
    "id": "047",
    "title": "Addressing modes and operand interpretation",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 48,
    "id": "048",
    "title": "Interrupts and interrupt service routines",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 49,
    "id": "049",
    "title": "Performance factors: cores, cache, clock speed and word length",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 50,
    "id": "050",
    "title": "Pipelining and why faster is not always simpler",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 51,
    "id": "051",
    "title": "Section 4 review: tracing processor behaviour",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 52,
    "id": "052",
    "title": "System software overview: operating systems, utility software and translators",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 53,
    "id": "053",
    "title": "Operating system roles: process, memory, file and device management",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 54,
    "id": "054",
    "title": "User interfaces: command line, graphical, menu-driven and natural language",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 55,
    "id": "055",
    "title": "Utility software: backup, compression, encryption, defragmentation and antivirus",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 56,
    "id": "056",
    "title": "Compilers, interpreters and assemblers",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 57,
    "id": "057",
    "title": "Compilation stages: lexical analysis to object code",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 58,
    "id": "058",
    "title": "Linkers, loaders and libraries",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 59,
    "id": "059",
    "title": "Error types: syntax, logic, runtime and translation diagnostics",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 60,
    "id": "060",
    "title": "Choosing translation approaches for development and deployment",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 61,
    "id": "061",
    "title": "Section 5 review: precise software comparisons",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 62,
    "id": "062",
    "title": "Security goals: confidentiality, integrity, availability and authenticity",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 63,
    "id": "063",
    "title": "Malware types and social engineering",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 64,
    "id": "064",
    "title": "Hacking, phishing, pharming, and denial-of-service attacks",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 65,
    "id": "065",
    "title": "Authentication: passwords, biometrics, tokens, and MFA",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 66,
    "id": "066",
    "title": "Access rights, permissions, and least privilege",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 67,
    "id": "067",
    "title": "Encryption, hashing, and digital certificates",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 68,
    "id": "068",
    "title": "Firewalls, proxies, and network monitoring",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 69,
    "id": "069",
    "title": "Data validation and verification",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 70,
    "id": "070",
    "title": "Backup strategies, disaster recovery, and audit trails",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 71,
    "id": "071",
    "title": "Section 6 review: matching risks to controls",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 72,
    "id": "072",
    "title": "Ethical issues in Computer Science decisions",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 73,
    "id": "073",
    "title": "Privacy, surveillance, and data protection",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 74,
    "id": "074",
    "title": "Intellectual property, copyright, patents, and licensing",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 75,
    "id": "075",
    "title": "Open source, proprietary software, and ownership trade-offs",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 76,
    "id": "076",
    "title": "Environmental and social impacts of computing",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 77,
    "id": "077",
    "title": "Section 7 review: balanced evaluation answers",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 78,
    "id": "078",
    "title": "Data, information, databases and DBMS roles",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 79,
    "id": "079",
    "title": "Flat-file databases vs relational databases",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 80,
    "id": "080",
    "title": "Tables, records, fields, data types and constraints",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 81,
    "id": "081",
    "title": "Primary keys, foreign keys and relationships",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 82,
    "id": "082",
    "title": "Entity-relationship modelling",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 83,
    "id": "083",
    "title": "Normalisation: avoiding duplication and update problems",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 84,
    "id": "084",
    "title": "SQL SELECT, FROM, WHERE",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 85,
    "id": "085",
    "title": "SQL ORDER BY, aggregate functions and GROUP BY",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 86,
    "id": "086",
    "title": "SQL joins using related tables",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 87,
    "id": "087",
    "title": "SQL INSERT, UPDATE and DELETE",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 88,
    "id": "088",
    "title": "Validation, verification, security and backup in databases",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 89,
    "id": "089",
    "title": "Section 8 review: designing and querying relational data",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 90,
    "id": "090",
    "title": "Paper 1 review: representation and communication",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 91,
    "id": "091",
    "title": "Paper 1 review: hardware and processor fundamentals",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 92,
    "id": "092",
    "title": "Paper 1 review: system software and security",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 93,
    "id": "093",
    "title": "Paper 1 review: ethics and databases",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 94,
    "id": "094",
    "title": "Paper 1 mixed question strategy",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 95,
    "id": "095",
    "title": "Paper 1 timed short-answer practice",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 96,
    "id": "096",
    "title": "Paper 1 extended-response practice",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 97,
    "id": "097",
    "title": "Paper 1 mock review and correction clinic",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 98,
    "id": "098",
    "title": "Algorithmic thinking: inputs, outputs, and constraints",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 99,
    "id": "099",
    "title": "Decomposition and abstraction",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 100,
    "id": "100",
    "title": "Flowcharts and pseudocode notation",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 101,
    "id": "101",
    "title": "Trace tables and dry runs",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 102,
    "id": "102",
    "title": "Sequence, selection, and iteration in algorithms",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 103,
    "id": "103",
    "title": "Validation algorithms and defensive input handling",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 104,
    "id": "104",
    "title": "Linear search and binary search",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 105,
    "id": "105",
    "title": "Bubble sort and insertion sort",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 106,
    "id": "106",
    "title": "Maximum, minimum, count and total",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 107,
    "id": "107",
    "title": "String-processing algorithms",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 108,
    "id": "108",
    "title": "Nested loops and table-style problems",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 109,
    "id": "109",
    "title": "Algorithm efficiency at AS level",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 110,
    "id": "110",
    "title": "Cambridge pseudocode conventions and exam readability",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 111,
    "id": "111",
    "title": "Designing algorithms from word problems",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 112,
    "id": "112",
    "title": "Section 9 review: from scenario to pseudocode",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 113,
    "id": "113",
    "title": "Data types: integer, real, Boolean, char, string, date and user-defined types",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 114,
    "id": "114",
    "title": "Constants, variables and assignment",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 115,
    "id": "115",
    "title": "One-dimensional arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 116,
    "id": "116",
    "title": "Two-dimensional arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 117,
    "id": "117",
    "title": "Array algorithms: traversal, update, search and count",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 118,
    "id": "118",
    "title": "Records and composite data",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 119,
    "id": "119",
    "title": "Arrays of records",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 120,
    "id": "120",
    "title": "Text files: reading, writing and appending",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 121,
    "id": "121",
    "title": "CSV-style structured text files",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 122,
    "id": "122",
    "title": "Stacks and queues as abstract data types",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 123,
    "id": "123",
    "title": "Choosing appropriate data structures",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 124,
    "id": "124",
    "title": "Pseudocode data declarations vs Java declarations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 125,
    "id": "125",
    "title": "Section 10 review: data modelling in algorithms",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 126,
    "id": "126",
    "title": "Programming constructs: sequence, selection and iteration",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 127,
    "id": "127",
    "title": "IF, CASE and nested selection",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 128,
    "id": "128",
    "title": "Count-controlled loops",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 129,
    "id": "129",
    "title": "Condition-controlled loops",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 130,
    "id": "130",
    "title": "Procedures and functions",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 131,
    "id": "131",
    "title": "Parameters: by value and by reference",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 132,
    "id": "132",
    "title": "Scope, lifetime, and local/global variables",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 133,
    "id": "133",
    "title": "String handling and built-in functions",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 134,
    "id": "134",
    "title": "Arithmetic operators, integer division, and MOD",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 135,
    "id": "135",
    "title": "Input and output formatting",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 136,
    "id": "136",
    "title": "File handling patterns in pseudocode and Java",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 137,
    "id": "137",
    "title": "Testing with normal, boundary, and erroneous data",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 138,
    "id": "138",
    "title": "Debugging using traces and breakpoints",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 139,
    "id": "139",
    "title": "Robust program design: validation and modularity",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 140,
    "id": "140",
    "title": "Converting Java habits into Cambridge pseudocode",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 141,
    "id": "141",
    "title": "Section 11 review: writing complete program fragments",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 142,
    "id": "142",
    "title": "Software development lifecycle models",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 143,
    "id": "143",
    "title": "Requirements analysis and success criteria",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 144,
    "id": "144",
    "title": "Design documentation: algorithms, data dictionaries, and interfaces",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 145,
    "id": "145",
    "title": "Testing, implementation, maintenance, and evaluation",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 146,
    "id": "146",
    "title": "Section 12 review: software development case study",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 147,
    "id": "147",
    "title": "Paper 2 review: algorithm design and data structures",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  },
  {
    "number": 148,
    "id": "148",
    "title": "Paper 2 review: programming constructs and file handling",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  },
  {
    "number": 149,
    "id": "149",
    "title": "Paper 2 timed pseudocode practice",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  },
  {
    "number": 150,
    "id": "150",
    "title": "Paper 2 mock review and correction clinic",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  }
];
  for (const lesson of lessons) Object.freeze(lesson);
  globalThis.AS9618CourseCatalog = Object.freeze(lessons);
}());
