/* Generated by scripts/render-course-v2.mjs. */
(function () {
  "use strict";
  const lessons = [
  {
    "number": 1,
    "id": "001",
    "title": "Binary data units and magnitude prefixes",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 2,
    "id": "002",
    "title": "Binary, denary and hexadecimal number systems",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 3,
    "id": "003",
    "title": "Signed binary arithmetic and overflow",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 4,
    "id": "004",
    "title": "BCD, hexadecimal applications and character encoding",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 5,
    "id": "005",
    "title": "Bitmap and vector graphics",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 6,
    "id": "006",
    "title": "Sound representation and file compression",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 7,
    "id": "007",
    "title": "Network purposes, LANs, WANs and computer roles",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 8,
    "id": "008",
    "title": "Network topologies and packet transmission",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 9,
    "id": "009",
    "title": "Cloud computing and transmission media",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 10,
    "id": "010",
    "title": "LAN hardware, routers and Ethernet",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 11,
    "id": "011",
    "title": "Streaming, the internet and connection infrastructure",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 12,
    "id": "012",
    "title": "IP addressing, subnetting, URLs and DNS",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 13,
    "id": "013",
    "title": "Input, output, storage and embedded systems",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 14,
    "id": "014",
    "title": "How input, output and storage devices work",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 15,
    "id": "015",
    "title": "Buffers and primary memory technologies",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 16,
    "id": "016",
    "title": "Monitoring, control, sensors and actuators",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 17,
    "id": "017",
    "title": "Logic gates, symbols and truth tables",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 18,
    "id": "018",
    "title": "Boolean expressions and logic-circuit design",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 19,
    "id": "019",
    "title": "Von Neumann architecture, CPU components and registers",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 20,
    "id": "020",
    "title": "System buses, ports and processor performance",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 21,
    "id": "021",
    "title": "The fetch-execute cycle in register-transfer notation",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 22,
    "id": "022",
    "title": "Interrupt causes, detection and handling",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 23,
    "id": "023",
    "title": "Assembly language and the two-pass assembler",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 24,
    "id": "024",
    "title": "Tracing instructions and addressing modes",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 25,
    "id": "025",
    "title": "Bit manipulation, masks and binary shifts",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 26,
    "id": "026",
    "title": "Why operating systems are required",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 27,
    "id": "027",
    "title": "Utility software, libraries and linked files",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 28,
    "id": "028",
    "title": "Assemblers, compilers and interpreters",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 29,
    "id": "029",
    "title": "Choosing a translator and understanding Java translation",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 30,
    "id": "030",
    "title": "IDE features and practical debugging support",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 31,
    "id": "031",
    "title": "Security, privacy, integrity and the need for protection",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 32,
    "id": "032",
    "title": "Internet threats, malware and access restriction",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 33,
    "id": "033",
    "title": "Authentication, encryption and network protection",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 34,
    "id": "034",
    "title": "Validation, verification, parity and checksums",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 35,
    "id": "035",
    "title": "Professional ethics and professional bodies",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 36,
    "id": "036",
    "title": "Ethical decisions and their consequences",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 37,
    "id": "037",
    "title": "Copyright and software licences",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 38,
    "id": "038",
    "title": "Artificial intelligence applications and impacts",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 39,
    "id": "039",
    "title": "From file-based systems to relational databases",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 40,
    "id": "040",
    "title": "Entity-relationship design and normalisation",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 41,
    "id": "041",
    "title": "DBMS architecture, integrity, security and backup",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 42,
    "id": "042",
    "title": "DDL, DML and the role of SQL",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 43,
    "id": "043",
    "title": "Reading and writing SQL queries",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 44,
    "id": "044",
    "title": "Creating and maintaining database data",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 45,
    "id": "045",
    "title": "Paper 1 integrated review and error clinic",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 46,
    "id": "046",
    "title": "Abstraction and abstract models",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 47,
    "id": "047",
    "title": "Decomposition and modular problem solving",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 48,
    "id": "048",
    "title": "Algorithms and meaningful identifiers",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 49,
    "id": "049",
    "title": "Input-process-output solution design",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 50,
    "id": "050",
    "title": "Sequence, selection and iteration",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 51,
    "id": "051",
    "title": "Structured English, flowcharts and pseudocode",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 52,
    "id": "052",
    "title": "Stepwise refinement",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 53,
    "id": "053",
    "title": "Constructing and interpreting logic statements",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 54,
    "id": "054",
    "title": "Integrated algorithm design from a word problem",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 55,
    "id": "055",
    "title": "Cambridge data types and declarations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 56,
    "id": "056",
    "title": "Records: defining, reading and saving structured data",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 57,
    "id": "057",
    "title": "Array terminology, indices and bounds",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 58,
    "id": "058",
    "title": "Selecting and using one-dimensional arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 59,
    "id": "059",
    "title": "Selecting and using two-dimensional arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 60,
    "id": "060",
    "title": "Linear search using arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 61,
    "id": "061",
    "title": "Bubble sort using arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 62,
    "id": "062",
    "title": "Why files are needed and text-file pseudocode",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 63,
    "id": "063",
    "title": "Abstract data types",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 64,
    "id": "064",
    "title": "Stacks and LIFO operations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 65,
    "id": "065",
    "title": "Queues and FIFO operations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 66,
    "id": "066",
    "title": "Linked-list features and operations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 67,
    "id": "067",
    "title": "Implementing ADT operations with arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 68,
    "id": "068",
    "title": "Choosing and combining data structures",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 69,
    "id": "069",
    "title": "Translating descriptions into Cambridge pseudocode",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 70,
    "id": "070",
    "title": "Declarations, assignment and input/output",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 71,
    "id": "071",
    "title": "Arithmetic and logical expressions",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 72,
    "id": "072",
    "title": "Built-in routines and string functions",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 73,
    "id": "073",
    "title": "IF, ELSE and CASE selection",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 74,
    "id": "074",
    "title": "Count-controlled iteration",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 75,
    "id": "075",
    "title": "Pre-condition and post-condition loops",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 76,
    "id": "076",
    "title": "Selecting and justifying a loop structure",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 77,
    "id": "077",
    "title": "Procedures and parameter passing",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 78,
    "id": "078",
    "title": "Functions, interfaces and return values",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 79,
    "id": "079",
    "title": "Clear and efficient Cambridge pseudocode",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 80,
    "id": "080",
    "title": "Writing complete program fragments",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 81,
    "id": "081",
    "title": "Program-development lifecycle models",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 82,
    "id": "082",
    "title": "Structure charts and module interfaces",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 83,
    "id": "083",
    "title": "State-transition diagrams",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 84,
    "id": "084",
    "title": "Finding and correcting program errors",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 85,
    "id": "085",
    "title": "Testing methods through the development process",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 86,
    "id": "086",
    "title": "Test strategies and test plans",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 87,
    "id": "087",
    "title": "Normal, abnormal and boundary test data",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 88,
    "id": "088",
    "title": "Corrective, adaptive and perfective maintenance",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 89,
    "id": "089",
    "title": "Analysing and amending an existing program",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 90,
    "id": "090",
    "title": "Paper 2 integrated review and pseudocode clinic",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  }
];
  for (const lesson of lessons) Object.freeze(lesson);
  globalThis.AS9618CourseCatalog = Object.freeze(lessons);
}());
