/* Generated by scripts/generate-course-catalog.mjs. Do not edit by hand. */
(function () {
  "use strict";
  const lessons = [
  {
    "number": 1,
    "id": "001",
    "title": "Binary and decimal magnitude prefixes",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 2,
    "id": "002",
    "title": "Integer conversion between binary and denary",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 3,
    "id": "003",
    "title": "Hexadecimal as a base-16 representation",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 4,
    "id": "004",
    "title": "Binary addition and fixed-width overflow",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 5,
    "id": "005",
    "title": "Signed representations and binary subtraction",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 6,
    "id": "006",
    "title": "BCD and hexadecimal in practical systems",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 7,
    "id": "007",
    "title": "Character sets and internal binary character data",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 8,
    "id": "008",
    "title": "Bitmap file headers, image resolution and screen resolution",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 9,
    "id": "009",
    "title": "Vector graphics and drawing lists",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 10,
    "id": "010",
    "title": "Sound sampling, sampling resolution, accuracy and storage",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 11,
    "id": "011",
    "title": "Sound file size calculations",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 12,
    "id": "012",
    "title": "Compression methods for text, bitmap, vector and sound files",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 13,
    "id": "013",
    "title": "Run-length encoding and dictionary-style compression",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 14,
    "id": "014",
    "title": "Choosing data representation for a real system",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 15,
    "id": "015",
    "title": "Section 1 review under exam timing",
    "paper": "Paper 1",
    "section": "Section 1",
    "unitId": "section-1",
    "unitTitle": "Information representation"
  },
  {
    "number": 16,
    "id": "016",
    "title": "Network purpose and client/server models",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 17,
    "id": "017",
    "title": "Bus, star, mesh and hybrid topologies",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 18,
    "id": "018",
    "title": "Packet transmission between two hosts in each required topology",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 19,
    "id": "019",
    "title": "Cloud, wired and wireless networking",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 20,
    "id": "020",
    "title": "LAN hardware, Ethernet, streaming, the internet, IP and URL",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 21,
    "id": "021",
    "title": "LAN hardware and the router",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 22,
    "id": "022",
    "title": "Ethernet collisions and CSMA/CD",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 23,
    "id": "023",
    "title": "Bit streaming, bit rate and broadband",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 24,
    "id": "024",
    "title": "The internet and the World Wide Web",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 25,
    "id": "025",
    "title": "Internet connection hardware",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 26,
    "id": "026",
    "title": "IP addressing, URL structure and DNS",
    "paper": "Paper 1",
    "section": "Section 2",
    "unitId": "section-2",
    "unitTitle": "Communication"
  },
  {
    "number": 27,
    "id": "027",
    "title": "Why computer systems need input, output and storage",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 28,
    "id": "028",
    "title": "Embedded systems: purpose, benefits and drawbacks",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 29,
    "id": "029",
    "title": "Microphone, touchscreen and VR headset operation",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 30,
    "id": "030",
    "title": "Output, storage devices and primary memory",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 31,
    "id": "031",
    "title": "Monitoring, control, feedback and required sensors",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 32,
    "id": "032",
    "title": "Logic-gate symbols, functions and representation conversions",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 33,
    "id": "033",
    "title": "Monitoring, control, feedback and required sensors",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 34,
    "id": "034",
    "title": "Logic-gate symbols, functions and representation conversions",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 35,
    "id": "035",
    "title": "Logic gates: NOT, AND, OR, NAND, NOR, XOR",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 36,
    "id": "036",
    "title": "Truth tables and Boolean expressions",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 37,
    "id": "037",
    "title": "Building logic circuits from requirements",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 38,
    "id": "038",
    "title": "Hardware selection for different users",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 39,
    "id": "039",
    "title": "Environmental and reliability considerations in hardware",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 40,
    "id": "040",
    "title": "Section 3 review: compare, justify, calculate",
    "paper": "Paper 1",
    "section": "Section 3",
    "unitId": "section-3",
    "unitTitle": "Hardware"
  },
  {
    "number": 41,
    "id": "041",
    "title": "Von Neumann architecture, CPU components and registers",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 42,
    "id": "042",
    "title": "System buses, ports and processor performance",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 43,
    "id": "043",
    "title": "Register-transfer notation for the fetch-decode-execute cycle",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 44,
    "id": "044",
    "title": "Interrupt causes, detection and handling",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 45,
    "id": "045",
    "title": "Assembly language and machine code",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 46,
    "id": "046",
    "title": "Two-pass assembly, program tracing and the instruction set",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 47,
    "id": "047",
    "title": "Addressing modes and address-sensitive instructions",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 48,
    "id": "048",
    "title": "Section 4 semantic checkpoint",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 49,
    "id": "049",
    "title": "Bit manipulation with masks and shifts",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 50,
    "id": "050",
    "title": "Bit manipulation: masks and binary shifts",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 51,
    "id": "051",
    "title": "Section 4 review: tracing processor behaviour",
    "paper": "Paper 1",
    "section": "Section 4",
    "unitId": "section-4",
    "unitTitle": "Processor fundamentals"
  },
  {
    "number": 52,
    "id": "052",
    "title": "Why an operating system is required and what it manages",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 53,
    "id": "053",
    "title": "Required utility software",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 54,
    "id": "054",
    "title": "Libraries and dynamically linked library files",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 55,
    "id": "055",
    "title": "Assembler, compiler and interpreter choices",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 56,
    "id": "056",
    "title": "Java translation and required IDE features",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 57,
    "id": "057",
    "title": "Compilation stages: lexical analysis to object code",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 58,
    "id": "058",
    "title": "Linkers, loaders and libraries",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 59,
    "id": "059",
    "title": "Error types: syntax, logic, runtime and translation diagnostics",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 60,
    "id": "060",
    "title": "Choosing translation approaches for development and deployment",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 61,
    "id": "061",
    "title": "Section 5 review: precise software comparisons",
    "paper": "Paper 1",
    "section": "Section 5",
    "unitId": "section-5",
    "unitTitle": "System software"
  },
  {
    "number": 62,
    "id": "062",
    "title": "Security, privacy and data integrity",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 63,
    "id": "063",
    "title": "Virus, spyware, anti-virus and anti-spyware",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 64,
    "id": "064",
    "title": "Required internet threats and matching risk-reduction methods",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 65,
    "id": "065",
    "title": "User accounts, passwords and biometric authentication",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 66,
    "id": "066",
    "title": "Access rights and encryption as data-security methods",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 67,
    "id": "067",
    "title": "Digital signatures and encryption",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 68,
    "id": "068",
    "title": "Firewall protection from a stand-alone PC to a network",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 69,
    "id": "069",
    "title": "Complete validation and verification methods",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 70,
    "id": "070",
    "title": "Backup strategies, disaster recovery, and audit trails",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 71,
    "id": "071",
    "title": "Section 6 review: matching risks to controls",
    "paper": "Paper 1",
    "section": "Section 6",
    "unitId": "section-6",
    "unitTitle": "Security, privacy and data integrity"
  },
  {
    "number": 72,
    "id": "072",
    "title": "Professional ethics, professional bodies and ethical decisions",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 73,
    "id": "073",
    "title": "Privacy, surveillance, and data protection",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 74,
    "id": "074",
    "title": "Copyright legislation, FSF, OSI and licence permissions",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 75,
    "id": "075",
    "title": "Shareware and commercial licences",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 76,
    "id": "076",
    "title": "AI applications and impact chains",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 77,
    "id": "077",
    "title": "Section 7 required-content checkpoint",
    "paper": "Paper 1",
    "section": "Section 7",
    "unitId": "section-7",
    "unitTitle": "Ethics and ownership"
  },
  {
    "number": 78,
    "id": "078",
    "title": "File-based limitations and relational solutions",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 79,
    "id": "079",
    "title": "Relational terminology, keys and relationships",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 80,
    "id": "080",
    "title": "E-R design, normalisation and DBMS features",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 81,
    "id": "081",
    "title": "First, second and third normal form",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 82,
    "id": "082",
    "title": "DBMS features and practical software tools",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 83,
    "id": "083",
    "title": "DDL, DML and SQL roles",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 84,
    "id": "084",
    "title": "Read and write SQL statements by their semantics",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 85,
    "id": "085",
    "title": "DDL and two-table data queries",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 86,
    "id": "086",
    "title": "Two-table INNER JOIN queries",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 87,
    "id": "087",
    "title": "INSERT, DELETE and UPDATE",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 88,
    "id": "088",
    "title": "Validation, verification, security and backup in databases",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 89,
    "id": "089",
    "title": "Section 8 required-content checkpoint",
    "paper": "Paper 1",
    "section": "Section 8",
    "unitId": "section-8",
    "unitTitle": "Databases"
  },
  {
    "number": 90,
    "id": "090",
    "title": "Paper 1 review: representation and communication",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 91,
    "id": "091",
    "title": "Paper 1 review: hardware and processor fundamentals",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 92,
    "id": "092",
    "title": "Paper 1 review: system software and security",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 93,
    "id": "093",
    "title": "Paper 1 review: ethics and databases",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 94,
    "id": "094",
    "title": "Paper 1 mixed question strategy",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 95,
    "id": "095",
    "title": "Paper 1 timed short-answer practice",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 96,
    "id": "096",
    "title": "Paper 1 extended-response practice",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 97,
    "id": "097",
    "title": "Paper 1 mock review and correction clinic",
    "paper": "Paper 1",
    "section": "Review",
    "unitId": "paper-1-review",
    "unitTitle": "Paper 1 integrated review"
  },
  {
    "number": 98,
    "id": "098",
    "title": "Abstraction and decomposition into program modules",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 99,
    "id": "099",
    "title": "Algorithms, IPO solutions and identifier tables",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 100,
    "id": "100",
    "title": "Sequence, selection and iteration",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 101,
    "id": "101",
    "title": "Structured English, flowcharts and pseudocode conversion",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 102,
    "id": "102",
    "title": "Stepwise refinement from IPO design to modules",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 103,
    "id": "103",
    "title": "Logic statements define parts of an algorithm",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 104,
    "id": "104",
    "title": "Linear search and binary search",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 105,
    "id": "105",
    "title": "Bubble sort and insertion sort",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 106,
    "id": "106",
    "title": "Maximum, minimum, count and total",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 107,
    "id": "107",
    "title": "String-processing algorithms",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 108,
    "id": "108",
    "title": "Nested loops and table-style problems",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 109,
    "id": "109",
    "title": "Algorithm efficiency at AS level",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 110,
    "id": "110",
    "title": "Cambridge pseudocode conventions and exam readability",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 111,
    "id": "111",
    "title": "Designing algorithms from word problems",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 112,
    "id": "112",
    "title": "Section 9 required-content checkpoint",
    "paper": "Paper 2",
    "section": "Section 9",
    "unitId": "section-9",
    "unitTitle": "Algorithm design and problem-solving"
  },
  {
    "number": 113,
    "id": "113",
    "title": "Select and use the official Cambridge data types",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 114,
    "id": "114",
    "title": "Define, read and save record data",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 115,
    "id": "115",
    "title": "Array terminology, selection and one-dimensional pseudocode",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 116,
    "id": "116",
    "title": "Select and write two-dimensional arrays",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 117,
    "id": "117",
    "title": "Array model required by search algorithms",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 118,
    "id": "118",
    "title": "Write linear-search and bubble-sort algorithms",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 119,
    "id": "119",
    "title": "Why files are needed and how text-file pseudocode works",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 120,
    "id": "120",
    "title": "Abstract data types and array-based operations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 121,
    "id": "121",
    "title": "Choosing stack, queue or linked list",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 122,
    "id": "122",
    "title": "Stacks and queues as abstract data types",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 123,
    "id": "123",
    "title": "Choosing appropriate data structures",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 124,
    "id": "124",
    "title": "Pseudocode data declarations vs Java declarations",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 125,
    "id": "125",
    "title": "Section 10 review: data modelling in algorithms",
    "paper": "Paper 2",
    "section": "Section 10",
    "unitId": "section-10",
    "unitTitle": "Data types and structures"
  },
  {
    "number": 126,
    "id": "126",
    "title": "Translate descriptions into Cambridge pseudocode",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 127,
    "id": "127",
    "title": "Complete Cambridge pseudocode statements",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 128,
    "id": "128",
    "title": "Use supplied built-in and library routines",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 129,
    "id": "129",
    "title": "Selection and loop structures",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 130,
    "id": "130",
    "title": "Procedures, functions and their interfaces",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 131,
    "id": "131",
    "title": "Pre-condition, post-condition and loop choice",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 132,
    "id": "132",
    "title": "Procedures, functions and their interfaces",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 133,
    "id": "133",
    "title": "Clear and efficient Cambridge pseudocode",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 134,
    "id": "134",
    "title": "Arithmetic operators, integer division, and MOD",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 135,
    "id": "135",
    "title": "Input and output formatting",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 136,
    "id": "136",
    "title": "File handling patterns in pseudocode and Java",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 137,
    "id": "137",
    "title": "Testing with normal, abnormal, and extreme/boundary data",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 138,
    "id": "138",
    "title": "Debugging using traces and breakpoints",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 139,
    "id": "139",
    "title": "Robust program design: validation and modularity",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 140,
    "id": "140",
    "title": "Converting Java habits into Cambridge pseudocode",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 141,
    "id": "141",
    "title": "Section 11 review: writing complete program fragments",
    "paper": "Paper 2",
    "section": "Section 11",
    "unitId": "section-11",
    "unitTitle": "Programming"
  },
  {
    "number": 142,
    "id": "142",
    "title": "Lifecycle models, purpose and limitations",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 143,
    "id": "143",
    "title": "Structure charts and the purpose of state-transition diagrams",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 144,
    "id": "144",
    "title": "Expose, locate and correct program errors",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 145,
    "id": "145",
    "title": "Testing, maintenance and enhancement",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 146,
    "id": "146",
    "title": "Maintenance and enhancement after delivery",
    "paper": "Paper 2",
    "section": "Section 12",
    "unitId": "section-12",
    "unitTitle": "Software development"
  },
  {
    "number": 147,
    "id": "147",
    "title": "Paper 2 review: algorithm design and data structures",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  },
  {
    "number": 148,
    "id": "148",
    "title": "Paper 2 review: programming constructs and file handling",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  },
  {
    "number": 149,
    "id": "149",
    "title": "Paper 2 timed pseudocode practice",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  },
  {
    "number": 150,
    "id": "150",
    "title": "Paper 2 mock review and correction clinic",
    "paper": "Paper 2",
    "section": "Review",
    "unitId": "paper-2-review",
    "unitTitle": "Paper 2 integrated review"
  }
];
  for (const lesson of lessons) Object.freeze(lesson);
  globalThis.AS9618CourseCatalog = Object.freeze(lessons);
}());
